### ISSUE TITLE
GooglePlay : Could not find 'libmmkv.so'

### ISSUE THREAD

**Issue by Pacyx** [Tencent/MMKV#1011]
平台 : Android 
打包方式: aab包(发布在谷歌商店)
依赖版本：
implementation 'com.tencent:mmkv:1.2.14'
implementation 'com.getkeepsafe.relinker:relinker:1.4.4'
MMKV初始化方式:
MMKV.initialize(this) { libName -> ReLinker.loadLibrary(applicationContext, libName) }
错误日志:
![image](https://user-images.githubusercontent.com/19285655/212292166-f3ba0613-3db8-443b-a196-d70d98f959bc.png)
![image](https://user-images.githubusercontent.com/19285655/212292195-72101880-1312-4daa-84ed-1dc5a90b62df.png)
![image](https://user-images.githubusercontent.com/19285655/212292250-b48fff97-cdb0-42e0-b2da-cc7a552b268c.png)

Caused by com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.a(ApkLibraryInstaller.java:27)
       at com.getkeepsafe.relinker.ReLinkerInstance.j(ReLinkerInstance.java:15)
       at com.getkeepsafe.relinker.ReLinkerInstance.i(ReLinkerInstance.java:3)
       at com.getkeepsafe.relinker.ReLinker.e(:5)
       at com.getkeepsafe.relinker.ReLinker.b(:1)
       at io.liuliu.music.InYuApplication.x(:9)
       at io.liuliu.music.InYuApplication.t()
       at io.liuliu.music.a.loadLibrary(:2)
       at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:1)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:20)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:8)
       at io.liuliu.music.InYuApplication.o(InYuApplication.kt:2)
       at io.liuliu.origin.BaseApp.onCreate(BaseApp.java:2)
       at io.liuliu.music.InYuApplication.onCreate(InYuApplication.kt:1)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6862)
       at android.app.ActivityThread.access$1600(ActivityThread.java:245)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7817)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

**Comment by Pacyx** [comment]
依赖版本
implementation 'com.tencent:mmkv:1.2.14'
implementation 'com.getkeepsafe.relinker:relinker:1.4.4'

**Comment by lingol** [comment]
We don't accept issues on UnSatisfied Link Error. Or, in your case, MissingLibraryException.
It's clearly not a library's problem but your project configuration problem, or App packaging problem.
