### ISSUE TITLE
java.lang.UnsatisfiedLinkError - dlopen failed: library "libc++_shared.so" not found

### ISSUE THREAD

**Issue by billdizl** [Tencent/MMKV#1023]
mmkv 1.2.15版本
 ndk {
               abiFilters 'arm64-v8a', 'armeabi-v7a'
            }

Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xx.xxCQbMXtSb6YxdZOy2KOqZfA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xx.xx-CQbMXtSb6YxdZOy2KOqZfA==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libc++_shared.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:119)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:108)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:71)

**Comment by lingol** [comment]
We no longer accept issues about `java.lang.UnsatisfiedLinkError`. It's clearly not a library developer's problem.
