### ISSUE TITLE
lib里有.so 但是依旧报这个错误，项目中没有armeabi这个。

### ISSUE THREAD

**Issue by hanhan500** [Tencent/MMKV#1067]
Caused by com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at com.marsgroup.one.baselib.utils.SharedPrefUtils.init$lambda-0(SharedPrefUtils.java:57)
       at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:189)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:159)
       at com.marsgroup.one.baselib.utils.SharedPrefUtils.init(SharedPrefUtils.java:57)
       at com.marsgroup.one.baselib.baseui.BaseApplication.onCreate(BaseApplication.kt:37)
       at cache.phonecleaner.junk.speedup.boost.android.App.safedk_App_onCreate_4e9c28dfbab8dc9f96f4998775386052(App.kt:1)
       at cache.phonecleaner.junk.speedup.boost.android.App.onCreate(App.kt:72)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
       at android.app.ActivityThread.access$1600(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by hanhan500** [comment]
不是每次都报这个错误，像Galaxy A21s，谷歌审核时候会报这个错误。

**Comment by lingol** [comment]
We don't accept issues with such errors anymore. It's clearly nothing for the library developer can do.
