### ISSUE TITLE
MMKV引起的ANR问题

### ISSUE THREAD

**Issue by ShireYin** [Tencent/MMKV#1102]
## Note:
ANR
主要分两类
一类是com.tencent.mmkv.MMKV.decodeXXX （decodeString等）
一类是com.tencent.mmkv.MMKV.getMMKVWithID

### The language of MMKV

>  Kotlin

### The version of MMKV

> v1.2.15 

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

> ANR
> 
main (native):tid=1 systid=21502 
#00 pc 0x41e04 base.apk + 15192064 (BuildId: dc828c4959e5084691965c5b8ede0e1929bd53cd)
       at com.tencent.mmkv.MMKV.decodeString(Native method)
       at com.tencent.mmkv.MMKV.getString(unavailable:7)
       at com.xiaomi.market.model.FirebaseConfig.getFirebaseConfigValue(FirebaseConfig.kt:8)
       at com.xiaomi.market.model.FirebaseConfig.getPrimitiveValue(FirebaseConfig.kt:1)
       at com.xiaomi.market.util.MarketUtils.shouldAlwaysBgServiceByAndroidVersion(MarketUtils.java:1)
       at com.xiaomi.market.util.MarketUtils.needAlwaysBackgroundService(MarketUtils.java:1)
       at com.xiaomi.market.util.ServiceUtils.startForegroundIfNeeded(ServiceUtils.java:7)
       at com.xiaomi.market.service.ForegroundService.onStartCommand(ForegroundService.java:1)
       at com.xiaomi.market.service.WaitAndRetryService.onStartCommand(WaitAndRetryService.java:1)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4789)
       at android.app.ActivityThread.access$2100(ActivityThread.java:273)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2165)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8302)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

main (native):tid=1 systid=5379 
#00 pc 0x2bb98 libartbase.so (std::__1::__function::__func<art::InitLogging(char**, void (&)(char const*))::LogdLoggerLocked, std::__1::allocator<art::InitLogging(char**, void (&)(char const*))::LogdLoggerLocked>, void (android::base::LogId, android::base::LogSeverity, char const*, char const*, unsigned int, char const*)>::operator()(android::base::LogId&&, android::base::LogSeverity&&, char const*&&, char const*&&, unsigned int&&, char const*&&) (.__uniq.85101241731209538599761260233789784808)) (BuildId: bc229634768e6487cee031f0b909ae43)
#01 pc 0x16d4c libbase.so (android::base::SetLogger(std::__1::function<void (android::base::LogId, android::base::LogSeverity, char const*, char const*, unsigned int, char const*)>&&)::$_2::__invoke(__android_log_message const*) + 192) (BuildId: 420d56eac27a210c92900f3ddb760c86)
#02 pc 0x69bc liblog.so (__android_log_write_log_message + 164) (BuildId: 467c2038cdfa767245f9280e657fdb85)
#03 pc 0x6c60 liblog.so (__android_log_print + 228) (BuildId: 467c2038cdfa767245f9280e657fdb85)
#04 pc 0x71c38 base.apk + 15114240 (BuildId: dc828c4959e5084691965c5b8ede0e1929bd53cd)
#05 pc 0x6028c base.apk + 15114240 (BuildId: dc828c4959e5084691965c5b8ede0e1929bd53cd)
#06 pc 0x5d2c0 base.apk + 15114240 (BuildId: dc828c4959e5084691965c5b8ede0e1929bd53cd)
#07 pc 0x5dc40 base.apk + 15114240 (BuildId: dc828c4959e5084691965c5b8ede0e1929bd53cd)
#08 pc 0x40e98 base.apk + 15114240 (BuildId: dc828c4959e5084691965c5b8ede0e1929bd53cd)
       at com.tencent.mmkv.MMKV.getMMKVWithID(Native method)
       at com.tencent.mmkv.MMKV.m0(MMKV.java:2)
       at com.xiaomi.market.preference.MMKVManager.getMMKV(MMKVManager.kt:9)
       at com.xiaomi.market.preference.MMKVManager.getMMKV(MMKVManager.kt:1)
       at com.xiaomi.market.util.PrefUtils.getSharedPref(PrefUtils.java:3)
       at com.xiaomi.market.util.PrefUtils.getSharedPrefFromParams(PrefUtils.java:4)
       at com.xiaomi.market.util.PrefUtils.getString(unavailable:5)
       at com.xiaomi.market.data.HostManager.init(HostManager.java:1)
       at com.xiaomi.market.data.HostManager.<init>(HostManager.java:5)
       at com.xiaomi.market.data.HostManager.getManager(HostManager.java:4)
       at com.xiaomi.market.conn.Connection.innerRequestOkHttp(Connection.java:18)
       at com.xiaomi.market.conn.Connection.requestUnsafe(Connection.java:35)
       at com.xiaomi.market.conn.Connection.request(Connection.java:2)
       at com.xiaomi.market.conn.Connection.requestString(Connection.java:3)
       at com.xiaomi.market.conn.Connection.requestJSON(Connection.java:1)
       at com.xiaomi.market.loader.CloudConfigLoader$1.load(CloudConfigLoader.java:3)
       at com.xiaomi.market.loader.CloudConfigLoader.loadData(CloudConfigLoader.java:3)
       at com.xiaomi.market.loader.CloudConfigLoader.loadData(CloudConfigLoader.java:1)
       at com.xiaomi.market.loader.AbstractDataLoader.loadSync(unavailable)
       at com.xiaomi.market.model.cloudconfig.CloudConfig.performConfigSync(CloudConfig.java:3)
       at com.xiaomi.market.model.cloudconfig.CloudConfig.syncConfigFromServer(CloudConfig.java:3)
       at com.xiaomi.market.model.cloudconfig.CloudConfig.getConfigOrSync(CloudConfig.java:3)
       at com.xiaomi.market.model.cloudconfig.CloudConfig.getOtherConfig(unavailable:9)
       at com.xiaomi.market.model.OtherConfig.get(OtherConfig.java:1)
       at com.xiaomi.market.data.AutoUpdateManager.shouldDelayAutoUpdate(AutoUpdateManager.java:2)
       at com.xiaomi.market.data.AutoUpdateManager.generatePendingList(AutoUpdateManager.java:12)
       at com.xiaomi.market.data.AutoUpdateManager.generatePendingList(AutoUpdateManager.java:1)
       at com.xiaomi.market.data.AutoUpdateManager.needDownloadInstallUpdate(AutoUpdateManager.java:1)
       at com.xiaomi.market.data.UpdateLevelManager.getNextCheckOrInstallInterval(UpdateLevelManager.java:1)
       at com.xiaomi.market.receiver.AutoUpdateScheduler.rescheduleConditionalCheck(AutoUpdateScheduler.java:2)
       at com.xiaomi.market.receiver.AutoUpdateScheduler.onStartJob(AutoUpdateScheduler.java:23)
       at android.app.job.JobService$1.onStartJob(JobService.java:62)
       at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:105)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8319)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by lingol** [comment]
The native call stacks are not inside libmmkv.so. Nothing we can do about it.

**Comment by kaitian521** [comment]
1、encodeXXX有没有在异步线程执行的？

**Comment by kaitian521** [comment]
我说一下我们项目关于ANR的发现吧，通过代码和打点猜测：MMKV在主线程执行了IO的系统调用导致了卡顿

### 1、getMMKVWithID 
这个函数会调用open函数去打开一个文件，Android在IO繁忙时，open很容易执行缓慢；我在线上发现很多相关的卡顿
![image](https://github.com/Tencent/MMKV/assets/1303341/6b16da4a-9de4-41bc-a269-bce6729fdac6)

尤其是当第一次创建文件的时候，牵涉到分配inode节点等情况，有时候会格外的慢：本地手机测试，文件存在的时候，open几乎是0ms，文件不存在的时候，open需要2ms

**这个问题倒是好解决，在子线程提前加载这个id的MMKV就行，所谓的文件预热**
**再就是不要用过多的id，尤其是把key和id搞迷糊了**

### 2、encodeXXX
尤其是encodeXXX比较多，我看了代码，也看了我们堆栈的调用路径，基本确定是下面原因：
当encode一个大value时，MMKV会不断以2倍扩容，直到大小满足要求；随后就是
`truncate`系统调用改变文件大小，在`zeroFillFile`中又执行了`lssek`和`write`系统调用将文件尾部清零；紧接着就是`unmap`和`map`系统调用重新映射。

众多的IO系统调用，加大了卡顿和ANR的概率。

这个问题不好解决，需要开发者注意，在一个id内，不要去存储太多的kv对，很容易膨胀；

或者MMKV在getMMKVWithID再增加一个文件初始大小的参数，直接把4K提高到自己想要的默认值，不过这个方法估计没多少人会用

### 3、decodeXXX
a、当多进程模式下，一个进程修改了值，另一个进程的seq检测了变化，就会重新loadFile；
b、当CRC校验失败的情况下，也会重新loadFile；
我负责的产品很少有decode相关的卡顿，可能是我们a和b都不大多的原因

**Comment by luzhiqian00** [comment]
在 GitHub 的 Issue #1102 中，用户报告了使用 MMKV 时引发的应用无响应（ANR）问题，主要涉及以下两种情况：

1. **`getMMKVWithID` 方法**：该方法会调用 `open` 函数打开文件。当 Android 系统 I/O 繁忙时，`open` 可能执行缓慢，导致卡顿。特别是在首次创建文件时，可能需要分配 inode 节点等操作，耗时可能更长。 

2. **`encodeXXX` 方法**：当编码一个较大的值时，MMKV 会不断以两倍扩容，直到满足需求。随后会调用 `truncate` 系统调用改变文件大小，并在 `zeroFillFile` 中执行 `lseek` 和 `write` 系统调用将文件尾部清零；紧接着会调用 `unmap` 和 `map` 系统调用重新映射。这些大量的 I/O 系统调用增加了卡顿和 ANR 的概率。 

**建议**：

- **`getMMKVWithID` 方法**：在子线程中提前加载对应 ID 的 MMKV 实例，进行文件预热。此外，避免使用过多的 ID，防止将 key 与 ID 混淆。 

- **`encodeXXX` 方法**：避免在单个 ID 下存储过多的键值对，防止数据膨胀；同时，尽量避免存储过长的字符串。 

总体而言，MMKV 作为小型键值存储工具，适用于存储小规模数据。开发者在使用时应注意其局限性，避免将其用作大型数据库，以防止性能问题。
