### ISSUE TITLE
Add compress for plain strings & alarm developer if file size is very big

### ISSUE THREAD

**Issue by kaitian521** [Tencent/MMKV#1103]
I report an issue that causing by incorrect use of MMKV, but we can do something for developers of MMKV, to avoid performance issue.

### The language of MMKV

JAVA

### The version of MMKV

1.3.0

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
Recently I found there are more ANR from MMKV

```
06-28 09:06:02.342
at com.tencent.mmkv.MMKV.encodeString(Native Method)
at com.tencent.mmkv.MMKV.encode(Proguard:6)
at com.A.tzcache.mmkv.MMKVAdapter.encode(Proguard:3)
at com.A.tzcache.TzCacheManager.encode(Proguard:1)
at com.A.tzeditor.activity.MainActivity.onSaveInstanceState(Proguard:11)
at android.app.Activity.performSaveInstanceState(Activity.java:2325)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1616)
at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6062)
at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5460)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5426)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5491)
at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
```

I dig into this problem, found that the string encoded is a json string which is about 500KB,
then I tried using gzip in JAVA to compress this string, after compress, the json string is reduced from 500K to 49K.
At luck, I seldom see this ANR in later version.

As a continuation, I send all MMKV file size of users to our server, I am shocked and surprised by the sizes of the file: the biggest one is 268M! it is huge waste for disk and memory because of using mmap which can consume many virtual memory

It must be the fault of our team!

**But I want to share something we can do for developers that not familiar with MMKV**

1、shall we add some gzip/zlib/snappy compressing for plain strings? just like [protobuf](url https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/io/gzip_stream.h)

I tested gzip, It has 11 times compress rate for plain json data

2、we can add some callbacks or alarms for developers if the MMKV file size is very big, so developers can do something to clear cache themself

Thanks.

**Comment by lingol** [comment]
No. We won't do it.
