### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String, int) (tried Java_com_tencent_mmkv_MMKV_jniInitialize and Java_com_tencent_mmkv_MMKV_jniInitialize__Ljava_lang_String_2I)

### ISSUE THREAD

**Issue by Croie** [Tencent/MMKV#1131]
### The version of MMKV
v1.2.8

### The platform of MMKV
 Android 8.1 vivo X20Plus UD

Issue: 
     E  No implementation found for void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String, int) (tried Java_com_tencent_mmkv_MMKV_jniInitialize and Java_com_tencent_mmkv_MMKV_jniInitialize__Ljava_lang_String_2I)
2023-08-10 10:22:02.129 16481-16481 AndroidRuntime          zygote64                             E  FATAL EXCEPTION: main
                                                                                                    Process: com.funbox.plus, PID: 16481
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String, int) (tried Java_com_tencent_mmkv_MMKV_jniInitialize and Java_com_tencent_mmkv_MMKV_jniInitialize__Ljava_lang_String_2I)
                                                                                                    	at com.tencent.mmkv.MMKV.jniInitialize(Native Method)
                                                                                                    	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:123)
                                                                                                    	at com.tencent.mmkv.MMKV.initialize(MMKV.java:108)
                                                                                                    	at com.tencent.mmkv.MMKV.initialize(MMKV.java:97)
                                                                                                    	at com.funbox.libcommon.DoFunApplication.initMMKV(DoFunApplication.kt:68)
                                                                                                    	at com.funbox.libcommon.DoFunApplication.onCreate(DoFunApplication.kt:42)
                                                                                                    	at com.funbox.plus.ThailandApplication.onCreate(ThailandApplication.kt:14)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5958)
                                                                                                    	at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:192)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6753)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)

**Comment by lingol** [comment]
Looks like you ProGuard MMKV the wrong way.

**Comment by Croie** [comment]
混淆内容我添加了，但还是报这个错（附：https://github.com/Tencent/MMKV/blob/master/Android/MMKV/proguard-rules/proguard-rules-android-lib.pro）添加的是这个文件的混淆内容

**Comment by lingol** [comment]
It's possible that your project has **multiple dependents on different versions of MMKV**. You can check on that. If it's true, upgrade all of them to **the latest version of MMKV**.

**Comment by Croie** [comment]
我这边依赖最新版本v1.3.1, 检查项目中的版本只依赖一个版本的情况下还是报错：

               E  ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                  E  │ Fail load MMKV .so : com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
                     E  │ 	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
                      E  │ 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
                      E  │ 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
 E  │ 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
                     E  │ 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
                      E  │ 	at com.funbox.libcommon.DoFunApplication.initMMKV$lambda$0(DoFunApplication.kt:83)
                     E  │ 	at com.funbox.libcommon.DoFunApplication.$r8$lambda$CYDFPxASPvm-nGkiZILG0gPeSUE(Unknown Source:0)
                      E  │ 	at com.funbox.libcommon.DoFunApplication$$ExternalSyntheticLambda0.loadLibrary(Unknown Source:2)
                     E  │ 	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:217)
                      E  │ 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:204)
                      E  │ 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:117)
                      E  │ 	at com.funbox.libcommon.DoFunApplication.initMMKV(DoFunApplication.kt:81)
                     E  │ 	at com.funbox.libcommon.DoFunApplication.onCreate(DoFunApplication.kt:50)
                   E  │ 	at com.funbox.plus.ThailandApplication.onCreate(ThailandApplication.kt:14)
                     E  │ 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
                     E  │ 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5958)
                    E  │ 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
                     E  │ 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
                      E  │ 	at android.os.Handler.dispatchMessage(Handler.java:106)
                      E  │ 	at android.os.Looper.loop(Looper.java:192)
                      E  │ 	at android.app.ActivityThread.main(ActivityThread.java:6753)
                      E  │ 	at java.lang.reflect.Method.invoke(Native Method)
                    E  │ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
                    E  │ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
                     E  └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   E  No implementation found for void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String, java.lang.String, int, boolean) (tried Java_com_tencent_mmkv_MMKV_jniInitialize and Java_com_tencent_mmkv_MMKV_jniInitialize__Ljava_lang_String_2Ljava_lang_String_2IZ)
                     E  FATAL EXCEPTION: main
                                                                                                    Process: com.funbox.plus, PID: 11059
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String, java.lang.String, int, boolean) (tried Java_com_tencent_mmkv_MMKV_jniInitialize and Java_com_tencent_mmkv_MMKV_jniInitialize__Ljava_lang_String_2Ljava_lang_String_2IZ)
                                                                                                    	at com.tencent.mmkv.MMKV.jniInitialize(Native Method)
                                                                                                    	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:224)
                                                                                                    	at com.tencent.mmkv.MMKV.initialize(MMKV.java:204)
                                                                                                    	at com.tencent.mmkv.MMKV.initialize(MMKV.java:117)
                                                                                                    	at com.funbox.libcommon.DoFunApplication.initMMKV(DoFunApplication.kt:81)
                                                                                                    	at com.funbox.libcommon.DoFunApplication.onCreate(DoFunApplication.kt:50)
                                                                                                    	at com.funbox.plus.ThailandApplication.onCreate(ThailandApplication.kt:14)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5958)
                                                                                                    	at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:192)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6753)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)


如上，而我的初始化在基类application代码如下：
![image](https://github.com/Tencent/MMKV/assets/13132992/f53088a2-8e91-44b5-b08e-701c52d88848)

**Comment by lingol** [comment]
>              E  │ Fail load MMKV .so : com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

The log is clear. Fixe it by yourself.

**Comment by Croie** [comment]
这款手机是arm64-v8a架构，打包安装是不会出现这种问题，直接ASdebug模式安装就存在上面问题 @
