### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError dlopen failed: library "libmmkv.so" not found

### ISSUE THREAD

**Issue by YaoBinZhang** [Tencent/MMKV#1164]
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:209)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:191)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:134)

**Comment by lingol** [comment]
We don't accept issues on UnsatisfiedLinkError anymore. It's clearly not a library developer's problem.
