### ISSUE TITLE
A native crash in colorOS-v1.3.1

### ISSUE THREAD

**Issue by Vensent** [Tencent/MMKV#1180]
### The language of MMKV

> Kotlin

### The version of MMKV

v1.3.1

### The platform of MMKV

> coloOS based on Android

### The installation of MMKV

>Maven

### What's the issue?

>a native crash

### What's the log of MMKV when that happened?
```
********** Crash dump: **********
Build fingerprint: 'OPPO/PFTM20/OP526D:13/TP1A.220905.001/S.129fad5-50d0:user/release-keys'
#00 0x0000000000078668 /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+296) (BuildId: cd953571180b7f5f8ae5570dad29595f)
#01 0x0000000000078d3c /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/lib/arm64/libmmkv.so (BuildId: a71d8dcfa9f4f3813b8cb9e938e9b1c76af7ab16)
                                                                                                                           memcpy(void*, void const* pass_object_size0, unsigned long)
                                                                                                                           /Users/lingol/Library/Android/sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/fortify/string.h:61:12
                                                                                                                           mmkv::CodedOutputData::writeRawData(mmkv::MMBuffer const&)
                                                                                                                           /Users/lingol/Developer/mmkv/Core/CodedOutputData.cpp:128:5
#02 0x0000000000078a74 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/lib/arm64/libmmkv.so (BuildId: a71d8dcfa9f4f3813b8cb9e938e9b1c76af7ab16)
                                                                                                                           mmkv::CodedOutputData::writeData(mmkv::MMBuffer const&)
                                                                                                                           /Users/lingol/Developer/mmkv/Core/CodedOutputData.cpp:78:11
#03 0x0000000000068054 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/lib/arm64/libmmkv.so (BuildId: a71d8dcfa9f4f3813b8cb9e938e9b1c76af7ab16)
                                                                                                                           MMKV::doAppendDataWithKey(mmkv::MMBuffer const&, mmkv::MMBuffer const&, bool, unsigned int)
                                                                                                                           /Users/lingol/Developer/mmkv/Core/MMKV_IO.cpp:774:19
#04 0x000000000006774c /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/lib/arm64/libmmkv.so (BuildId: a71d8dcfa9f4f3813b8cb9e938e9b1c76af7ab16)
                                                                                                                           MMKV::appendDataWithKey(mmkv::MMBuffer const&, mmkv::KeyValueHolder const&, bool)
                                                                                                                           /Users/lingol/Developer/mmkv/Core/MMKV_IO.cpp:825:12
#05 0x0000000000066fc4 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/lib/arm64/libmmkv.so (BuildId: a71d8dcfa9f4f3813b8cb9e938e9b1c76af7ab16)
                                                                                                                           MMKV::setDataForKey(mmkv::MMBuffer&&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, bool)
                                                                                                                           /Users/lingol/Developer/mmkv/Core/MMKV_IO.cpp:628:28
#06 0x000000000004cf60 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/lib/arm64/libmmkv.so (BuildId: a71d8dcfa9f4f3813b8cb9e938e9b1c76af7ab16)
                                                                                                                           MMKV::set(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, unsigned int)
                                                                                                                           /Users/lingol/Developer/mmkv/Core/MMKV.cpp:614:16
#07 0x000000000004ceac /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/lib/arm64/libmmkv.so (BuildId: a71d8dcfa9f4f3813b8cb9e938e9b1c76af7ab16)
                                                                                                                           MMKV::set(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
                                                                                                                           /Users/lingol/Developer/mmkv/Core/MMKV.cpp:605:12
#08 0x000000000004375c /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/lib/arm64/libmmkv.so (BuildId: a71d8dcfa9f4f3813b8cb9e938e9b1c76af7ab16)
                                                                                                                           mmkv::encodeString(_JNIEnv*, _jobject*, long, _jstring*, _jstring*)
                                                                                                                           /Users/lingol/Developer/mmkv/Android/MMKV/mmkv/src/main/cpp/native-bridge.cpp:557:35
#09 0x0000000000116740 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/oat/arm64/base.odex (art_jni_trampoline+144)
#10 0x000000000020a910 /apex/com.android.art/lib64/libart.so (nterp_helper+5648) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#11 0x000000000022fffc /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/base.apk (com.tencent.mmkv.MMKV.putString+4)
#12 0x000000000020b074 /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#13 0x000000000014c1f2 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/base.apk (com.oplus.mainlibcommon.SharedPreferencesProxy.J+42)
#14 0x000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#15 0x000000000014c13e /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/base.apk (com.oplus.mainlibcommon.SharedPreferencesProxy.K+22)
#16 0x0000000000209ae4 /apex/com.android.art/lib64/libart.so (nterp_helper+2020) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#17 0x000000000023a358 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/base.apk (com.coloros.gamespaceui.config.ServerConfigManager$a.h+100)
#18 0x000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#19 0x000000000023a89a /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/base.apk (com.coloros.gamespaceui.config.ServerConfigManager$pullSelfAccSupportList$1.invoke+22)
#20 0x000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#21 0x000000000023a848 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/base.apk (com.coloros.gamespaceui.config.ServerConfigManager$pullSelfAccSupportList$1.invoke+16)
#22 0x000000000020b074 /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#23 0x0000000000239322 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/base.apk (com.coloros.gamespaceui.config.CloudConfigService$c.a+106)
#24 0x000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#25 0x0000000000239280 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/base.apk (com.coloros.gamespaceui.config.CloudConfigService$c.invoke+4)
#26 0x00000000002c8694 /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/oat/arm64/base.odex (com.heytap.nearx.cloudconfig.observable.e.invoke+84)
#27 0x00000000001ff2ac /data/app/~~XrXbR---F_bnHleb4yZ1MQ==/com.oplus.games-o0kveFLs6oIj_vQJV8GUiQ==/oat/arm64/base.odex ([DEDUPED] ?.run+188)
#28 0x000000000032e410 /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+976) (BuildId: 1b9d4f55957fb3d4b1f58b5589e6d4dbe18626b8)
#29 0x000000000032b1f8 /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+72) (BuildId: 1b9d4f55957fb3d4b1f58b5589e6d4dbe18626b8)
#30 0x0000000000191cb0 /system/framework/arm64/boot.oat (java.lang.Thread.run+80) (BuildId: 1b9d4f55957fb3d4b1f58b5589e6d4dbe18626b8)
#31 0x000000000021096c /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#32 0x000000000027af68 /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#33 0x0000000000624cac /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#34 0x000000000066de60 /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1296) (BuildId: f9461dad2df8cf4e9114de5c4ff5caf5)
#35 0x00000000000eb720 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: cd953571180b7f5f8ae5570dad29595f)
#36 0x000000000007e2d0 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: cd953571180b7f5f8ae5570dad29595f)
```

**Comment by lingol** [comment]
It's crashed inside `memcpy()` according to your report. If you have correctly **configured the process mode of MMKV** then there are very little things we could do about it.

**Comment by kaitian521** [comment]
```
09-24 16:03:56.461 E/SQLiteDatabase(28113): android.database.sqlite.SQLiteFullException: database or disk is full (code 13 SQLITE_FULL)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:889)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1610)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1526)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.i0.k.a.k(Proguard:5)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.i0.p.d.b.q(Proguard:4)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.i0.d.i(Proguard:10)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.u.f.d(Proguard:1)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.u.f.c(Proguard:1)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.z.s.l(Proguard:4)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.z.s.j(Proguard:14)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.z.s$b.onError(Proguard:7)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.i0.d$b.onError(Proguard:3)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at b.a.u.i0.p.d.b$f.run(Proguard:3)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.os.Handler.handleCallback(Handler.java:883)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.os.Handler.dispatchMessage(Handler.java:100)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.os.Looper.loop(Looper.java:240)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at com.baidu.tzeditor.hook.FixDeadSystemExceptionHandler$1.run(Proguard:1)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.os.Handler.handleCallback(Handler.java:883)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.os.Handler.dispatchMessage(Handler.java:100)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.os.Looper.loop(Looper.java:240)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at android.app.ActivityThread.main(ActivityThread.java:7829)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at java.lang.reflect.Method.invoke(Native Method)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
09-24 16:03:56.461 E/SQLiteDatabase(28113): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
09-24 16:03:56.461 E/SQLiteLog(28113): (13) statement aborts at 27: [CREATE TABLE IF NOT EXISTS android_metadata (locale TEXT)] database or disk is full
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): signal 7 code 2
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): backtrace:
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): #0 pc 0x7f94c /apex/com.android.runtime/lib64/bionic/libc.so
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): #1 pc 0x66368 /data/app/com.baidu.tzeditor-WgVJKt5G6RdLAb1Jizz1LQ==/lib/arm64/libmmkv.so
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): #2 pc 0x641e0 /data/app/com.baidu.tzeditor-WgVJKt5G6RdLAb1Jizz1LQ==/lib/arm64/libmmkv.so
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): #3 pc 0x638dc /data/app/com.baidu.tzeditor-WgVJKt5G6RdLAb1Jizz1LQ==/lib/arm64/libmmkv.so
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): #4 pc 0x605e8 /data/app/com.baidu.tzeditor-WgVJKt5G6RdLAb1Jizz1LQ==/lib/arm64/libmmkv.so
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): #5 pc 0x60f74 /data/app/com.baidu.tzeditor-WgVJKt5G6RdLAb1Jizz1LQ==/lib/arm64/libmmkv.so
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): #6 pc 0x423e8 /data/app/com.baidu.tzeditor-WgVJKt5G6RdLAb1Jizz1LQ==/lib/arm64/libmmkv.so
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): #7 pc 0x6f70c1fd70 /data/app/com.baidu.tzeditor-WgVJKt5G6RdLAb1Jizz1LQ==/oat/arm64/base.odex
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): basic:
09-24 16:03:56.461 D/loki-native-NativeCrashHandler(28113): ABI: arm64 pid: 28113 tid: 28186
```

I guess, this crash happened when disk is full.
1、Assume we have a MMKV instance with 4K file size
2、we put a new key-value,  need expand, so a `ftruncate` is called, BUT `zeroFillFile` failed to write real bytes.
3、when restart,   `getFileSize` return the size after `ftruncate` which is a fake size.

May be we could  re`ftruncate` after `zeroFillFile` fails.
```
    if (m_size > oldSize) {
        if (!zeroFillFile(m_diskFile.m_fd, oldSize, m_size - oldSize)) {
            MMKVError("fail to zeroFile [%s] to size %zu, %s", m_diskFile.m_path.c_str(), m_size, strerror(errno));
            m_size = oldSize;
//TODO       ::ftruncate(m_diskFile.m_fd, static_cast<off_t>(oldSize));
            return false;
        }
    }
```

I am testing it now

**Comment by kaitian521** [comment]
<img width="1787" alt="image" src="https://github.com/Tencent/MMKV/assets/1303341/1bc37495-54ef-4375-8a85-8b0a78c3154b">

I reproduce this crash in Samsung S6 which is lack of disk

```
        new Thread(new Runnable() {
            @Override
            public void run() {
                MMKV mmkv = MMKV.mmkvWithID("disk_full");
                long i = 0;
                StringBuilder value = new StringBuilder();
                for (int j = 0; j < 100000; j++) {
                    value.append("a");
                }
                while (true) {
                    mmkv.encode(i++ + "", value.toString());
                }
            }
        }).start();
```

**Comment by Vensent** [comment]
Thanks a lot. @kaitian521 

Look forward the next MMKV version.
