### ISSUE TITLE
使用Nexus 5X手机android 8.1.0系统，发生崩溃事件

### ISSUE THREAD

**Issue by ningwenqiang** [Tencent/MMKV#1184]
使用Nexus 5X手机android 8.1.0系统，引用com.tencent:mmkv-static:1.2.10 版本
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hbxn.jackery-aeci2jPYKUGalv3LZINRnw==/base.apk"],nativeLibraryDirectories=[/data/app/com.hbxn.jackery-aeci2jPYKUGalv3LZINRnw==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libmmkv.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:8)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:17)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:28)
       at com.hbxn.jackery.app.AppApplication.q(AppApplication.java:1)
       at com.hbxn.jackery.app.AppApplication.onCreate_aroundBody0(AppApplication.java:3)
       at com.hbxn.jackery.app.AppApplication$AjcClosure1.run(AppApplication.java:12)
       at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:14)
       at com.hbxn.jackery.aop.LogAspect.aroundJoinPoint(LogAspect.java:7)
       at com.hbxn.jackery.app.AppApplication.onCreate(AppApplication.java:55)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by lingol** [comment]
We no longer accept issues on unsatisfied link error because it's clearly not a library developer's responsibility.
