### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by jzh1996** [Tencent/MMKV#1192]
## Note:
小部分机型（小米12，红米Note11 Pro）在用decodeParcelable取数据的时候内存溢出了，实际数据很小

### The language of MMKV

Kotlin

### The version of MMKV

 v1.3.1

### The platform of MMKV

 Android

### The installation of MMKV

 Maven

### What's the issue?

java.lang.OutOfMemoryError: Failed to allocate a 7988979480 byte allocation with 10088286 free bytes and 502MB until OOM, target footprint 20176574, growth limit 536870912
	at java.util.ArrayList.(ArrayList.java:166)
	at com.chami.libs_base.net.ComponentListData$Creator.createFromParcel(Unknown Source:91)
	at com.chami.libs_base.net.ComponentListData$Creator.createFromParcel(Unknown Source:0)
	at com.tencent.mmkv.MMKV.decodeParcelable(MMKV.java:901)
	at com.tencent.mmkv.MMKV.decodeParcelable(MMKV.java:868)
	at com.chami.chami.study.HomeStudyFragment$initView$4.invokeSuspend(HomeStudyFragment.kt:212)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:112)
	at androidx.lifecycle.DispatchQueue.dispatchAndEnqueue$lambda-2$lambda-1(DispatchQueue.kt:100)
	at androidx.lifecycle.DispatchQueue.$r8$lambda$G2ay370n_s_ksSHUJaD9zIU8eCw(Unknown Source:0)
	at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cd11325, Dispatchers.Main.immediate]

**Comment by lingol** [comment]
Complain it to Xiaomi or Android.
