### ISSUE TITLE
Unable to find "libmmkv.so" library in system process when using MMKV in multi-process mode

### ISSUE THREAD

**Issue by sbmatch** [Tencent/MMKV#1195]
### The language of MMKV

>Java

### The version of MMKV

> v1.3.1  

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?
This code is run as system through the app_process command
```
Context mContext = ContextUtils.createPackageContext(BuildConfig.APPLICATION_ID);
String rootPath = MMKV.initialize(mContext);
System.out.println("remoteProcessMMKV: "+rootPath);
MMKV remoteKv = MMKV.mmkvWithID("remoteWorkPref", MMKV.MULTI_PROCESS_MODE);
System.out.println(remoteKv.getString("deleteChannel", null));
```
My expectation:
I write the relevant information through mmkv on the app side and tried to get the information in the system process, but I encountered a crash.

### What's the log of MMKV when that happened?
>  *** FATAL EXCEPTION IN SYSTEM PROCESS: binder:7973_4
                                                                            java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
                                                                            	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                            	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                            	at java.lang.System.loadLibrary(System.java:1661)
                                                                            	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:222)
                                                                            	at com.tencent.mmkv.MMKV.initialize(MMKV.java:204)
                                                                            	at com.tencent.mmkv.MMKV.initialize(MMKV.java:90)
                                                                            	at com.ma.notificationmgr.Main$1.onForegroundActivitiesChanged(Main.java:58)
                                                                            	at android.app.IProcessObserver$Stub.onTransact(IProcessObserver.java:105)
                                                                            	at android.os.Binder.execTransactInternal(Binder.java:1290)
                                                                            	at android.os.Binder.execTransact(Binder.java:1249)

**Comment by sbmatch** [comment]
I encountered a new problem after using the ReLinker library
Crash Log：
6618-6618  AndroidRuntime          app_process                          E  *** FATAL EXCEPTION IN SYSTEM PROCESS: main
                                                                            com.getkeepsafe.relinker.MissingLibraryException: Could not find 'liblibmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
                                                                            	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
                                                                            	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
                                                                            	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                                                                            	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
                                                                            	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
                                                                            	at com.ma.notificationmgr.Main.main(Main.java:86)
                                                                            	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
                                                                            	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:366)

main Method:
```
 public static void main(String[] args) {

        if (Looper.getMainLooper() == null) {
            Looper.prepareMainLooper();
        }

        if (Binder.getCallingUid() == 0 || Binder.getCallingUid() == 1000 || Binder.getCallingUid() == 2000) {

            context = (Process.myUid() == 2000) ? ContextUtils.createPackageContext("com.android.shell") : (Context) ContextUtils.retrieveSystemContext();

            if (Process.myUid() == 2000 && packageManager.checkPermission("android.permission.STATUS_BAR_SERVICE", "com.android.shell") != PackageManager.PERMISSION_GRANTED){
                throw new SecurityException("The current process or UID:"+Binder.getCallingUid()+" does not have the permission");
            }

            Context mContext = ContextUtils.createPackageContext(BuildConfig.APPLICATION_ID);
            ReLinker.loadLibrary(mContext, "libmmkv");
            String rootPath = MMKV.initialize(mContext);

            serviceThread = new ServiceThread(SERVICE_NAME, args, rootPath);
            serviceThread.start();

        }

        Looper.loop();

    }
```
ServiceThread Class 
```
 private static class ServiceThread extends HandlerThread {
        String[] args;
        String rootPath;
        public ServiceThread(String name, String[] args, String rootPath) {
            super(name);
            this.setName(name);
            this.args = args;
            this.rootPath = rootPath;
        }

        @Override
        public synchronized void start() {
            super.start();
            handler = new Handler(serviceThread.getLooper());

            int pid = Process.myPid();
            int uid = Process.myUid();

            System.out.println("欢迎使用! uid:" + uid + " pid:" + pid);
            System.out.println("激活成功, 现在可以继续使用了");

            activitymanager.registerProcessObserver(processObserver);

            MMKV remoteKv = MMKV.mmkvWithID("remoteWorkPref", MMKV.MULTI_PROCESS_MODE);

            new FileObserverUtils(rootPath, new FileObserverUtils.OnFileChangeListener() {
                @Override
                public void onFileCreated(String folderPath, String fileName) {

                }

                @Override
                public void onFileDeleted(String folderPath, String fileName) {

                }

                @Override
                public void onFileModify(String folderPath, String fileName) {
                    String value = remoteKv.getString("deleteChannel", null);
                    System.out.println(value);
                }
            });

            List<ProcessInfo> processInfos = appProcessTopData(ShellUtils.execCommand("top -o NAME,PID,USER,COMMAND -q -b -n 1", false));
            for (ProcessInfo info : processInfos) {
                if (info.getProcessName().equals(SERVICE_NAME) && info.getPid() != pid) {
                    System.out.println("Info: Killing old process " + info.getPid() + "\n" + ShellUtils.execCommand("kill -9 " + info.getPid(), false));
                }
            }

        }
    }
```

**Comment by lingol** [comment]
You should search about how to load native lib for Apps running in a system process.
