### ISSUE TITLE
初始化so 崩溃

### ISSUE THREAD

**Issue by wanggangroger** [Tencent/MMKV#1203]
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libmmkv.so" needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace "clns-4"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
       at java.lang.System.loadLibrary(System.java:1661)
       at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:84)
       at com.transsnet.palmpay.util.SPUtils.<init>(SPUtils.java:64)
       at com.transsnet.palmpay.util.SPUtils.getInstance(SPUtils.java:55)
       at com.transsnet.palmpay.core.task.SyncPushMessageTask.getPushMessageHistory(SyncPushMessageTask.java:89)
       at com.transsnet.palmpay.core.task.SyncPushMessageTask.checkPushMessageHistory(SyncPushMessageTask.java:78)
       at com.transsnet.palmpay.push.service.PalmPayInstanceIdService.handleDataMessage(PalmPayInstanceIdService.java:208)
       at com.transsnet.palmpay.push.service.PalmPayInstanceIdService.onReceivePassThroughMessage(PalmPayInstanceIdService.java:130)
       at com.transsnet.palmpay.push.service.PalmPayInstanceIdService.onMessageReceived(PalmPayInstanceIdService.java:65)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:235)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:185)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0(EnhancedIntentService.java:78)
       at com.google.firebase.messaging.EnhancedIntentService.$r8$lambda$NSk2h75eWhBOI4TsAFgvvtv1g9o(EnhancedIntentService.java)
       at androidx.camera.core.ImageCapture$$InternalSyntheticLambda$0$3b7efcf98e5584aa9dd7fc53ad0b7d78b0d3c2673580ac8e08fde077d4b18061$0.run$bridge(ImageCapture.java:66)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by lingol** [comment]
We no longer accept issues about `java.lang.UnsatisfiedLinkError`, because it's not a lib developer's problem.

**Comment by lingol** [comment]
https://www.google.com/search?q=is+not+accessible+for+the+namespace&sourceid=chrome&ie=UTF-8

**Comment by chy116449859** [comment]
关键是native代码是mmkv的，比如我后面提的issuse里说的，JNI_OnLoad return -4时，咋办？
