### ISSUE TITLE
Bad JNI version returned from JNI_OnLoad

### ISSUE THREAD

**Issue by chy116449859** [Tencent/MMKV#1204]
报错信息：java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/user/0/com.seuic.kysy/app_lib/libmmkv.so": -4

	at java.lang.Runtime.load0(Runtime.java:928)
	at java.lang.System.load(System.java:1633)
	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
	at com.xxx.utils.MMKVUtil.lambda$initMMKV$0(MMKVUtil.java:14)

我们用的Shadow插件化框架，只在插件进程里有这个问题，报错集中在android9。最近版本升级到1.3.2，之前的老版本没有这个问题。

**Comment by lingol** [comment]
https://www.google.com.hk/search?q=Bad+JNI+version+returned+from+JNI_OnLoad&sourceid=chrome&ie=UTF-8

**Comment by lingol** [comment]
We no longer accept issues on `java.lang.UnsatisfiedLinkError `, it's not a lib dev problem.

**Comment by lingol** [comment]
https://www.google.com.hk/search?q=registerNativeMethods+fail&oq=registerNativeMethods+fail
