### ISSUE TITLE
UnsatisfiedLinkError with 1.3.5 and 1.3.6. No issues when using 1.3.4

### ISSUE THREAD

**Issue by dimitar71** [Tencent/MMKV#1342]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
Kotlin

### The version of MMKV
1.3.5 and 1.3.6

### The platform of MMKV
Android

### The installation of MMKV
Gradle/Maven

### What's the issue?
With `1.3.5` and `1.3.6` I am getting `java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found`

We are using with multi process mode, here is the line where it fails:
```
private val mmkv: MMKV = MMKV.initialize(appContext).run { MMKV.mmkvWithID(MMKV_FILE_NAME, MMKV.MULTI_PROCESS_MODE) }
```

**Note** that there are **no** such issues when using `1.3.4`.

### What's the log of MMKV when that happened?
Here is the exception we are getting, happens when app starts

```
FirebaseCrashlytics             I  No version control information found
WM-WrkMgrInitializer            D  Initializing WorkManager with default configuration.
WM-PackageManagerHelper         D  Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
WM-Schedulers                   D  Created SystemJobScheduler and enabled SystemJobService
CompatibilityChangeReporter     D  Compat change id reported: 160794467; UID 10031; state: ENABLED
[Koin]                          I  Started 59 definitions in 8.056186 ms
MMKV                            I  Enable checkProcessMode()
AndroidRuntime                  D  Shutting down VM
AndroidRuntime                  E  FATAL EXCEPTION: main
                                   Process: com.telus.stbtvclient, PID: 19533
                                   java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
                                   	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                   	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                   	at java.lang.System.loadLibrary(System.java:1656)
                                   	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
                                   	at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
                                   	at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
                                   	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                   	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                   	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                   	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                   	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                   	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                   	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
                                   	at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
                                   	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
                                   	at org.koin.core.scope.Scope.get(Scope.kt:21)
FirebaseCrashlytics             W  Unable to read App Quality Sessions session id.
Process                         I  Sending signal. PID: 19533 SIG: 9
```

**Comment by jzlhll** [comment]
1.3.5+ drop x86 and amv7.

**Comment by lingol** [comment]
> 1.3.5+ drop x86 and armV7.

That is right. You have two options. Either add armv8 support or build arvm7 binary of MMKV by yourself.

**Comment by dimitar71** [comment]
Thank you for your quickly responses.
I am going to do that and will inform here of the success/failure.

However, I personally think there should be a section somewhere there - https://github.com/Tencent/MMKV/wiki/android_setup.

Using it in a library module, we are expecting this to work out of the box.
It is for a vanilla Chromecast device, not some exotic unknown thingie done in a mom-and-pop basement/garage.

If not, to have a short tutorial/steps what needs to be done - with or w/o building from sources and alike.

Other than this recent problem, an excellent, if not best and its own league library.

**Comment by dimitar71** [comment]
OK, using the steps in https://github.com/Tencent/MMKV/wiki/android_setup > `Build From source` and it fails.

Using Android Studio Koala | 2024.1.1. 

Please provide fulls teps guide if possible, including Android Studio version, Gradle version, Java version, etc. for the ability to compile against your sources.

In the meantime, back to `1.3.4`.
<img width="1083" alt="Screenshot 2024-07-06 at 11 23 50 AM" src="https://github.com/Tencent/MMKV/assets/1563337/19af66e5-aa3e-4ee5-b433-66a444b44545">

**Comment by dimitar71** [comment]
After some tweaking, I could build from sources using latest Android Studio, Gradle and Kotlin.
There are some caveats, up to you to use these findings or not.

Attached is `MMKV-1.3.6/Android/MMKV` folder only as a zip, with the changes which allow me to build and use all arm additions.

---
# Everything from Android/MMKV
- using Android Studio Koala 2024.1.1
- creating the AAR builds via `Build > Make Project`
- `build.gradle`
    - `ext.kotlin_version = '2.0.0'`
    - `classpath 'com.android.tools.build:gradle:7.4.2'` - OK
    - `classpath 'com.android.tools.build:gradle:8.5.0'` - fails since BuildConfig is not generated
    - `minSdkVersion = 21` - must be added or fail
- `settings.gradle`
    - `include ':mmkv', 'mmkvannotation'` - removed `mmkvdemo` since some unit tests fail
- `gradle/build_library.gradle`
    - `// signingConfig signingConfigs.configDebug` - says key is tampered
- `gradle/wrapper/gradle-wrapper.properties`
    - `distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-all.zip`
- `mmkv/build.gradle`
    - `minSdkVersion rootProject.ext.minSdkVersion` - must be added or fail
- `mmkvannotation/build.gradle`
    - `minSdkVersion rootProject.ext.minSdkVersion` - must be added or fail
- dependency libs in all `build.gradle` files updated - please compare with original
- `Settings > Build, Execution, Deployment > Build Tools > Gradle > Gradke JDK`
    - default `jbr-27 JetBrains Runtime 17.0.10 /Applications/Android Studio.app/Contents/jbr/Contents/Home`

[MMKV-1.3.6.zip](https://github.com/user-attachments/files/16117392/MMKV-1.3.6.zip)

**Comment by lingol** [comment]
The removal of 32bit architecture is a well thought decision and will not be reversed.

Upon your changes, the changes to the abi filter is essential. Others are just environmental differences. 

I shall mention the steps to build a armv7 binary in the wiki if I haven't already done so.

**Comment by lingol** [comment]
[v1.3.7 LST](https://github.com/Tencent/MMKV/releases/tag/v1.3.7 ) has just been release.

**This Long Term Support (LTS) release** primarily reintroduces support for the ARMv7 architecture and lowers the minimum SDK version requirement to 21. Please note that only critical bug fixes will be applied to the 1.3.x series. 

New features will be introduced in version 2.0 and later, which will discontinue support for 32-bit architectures and raise the minimum SDK version requirement to 23.

**Comment by lingol** [comment]
One more thing, the wiki has been updated on building from source on Android. It will be helpful once we upgrade to v2.0+.
https://github.com/Tencent/MMKV/wiki/android_setup

**Comment by dimitar71** [comment]
Thank you!
