### ISSUE TITLE
Harmonry Next (API12 Beta3) crashed in release mode due to obfuscation

### ISSUE THREAD

**Issue by xiaoyaoyouzi163com** [Tencent/MMKV#1385]
```
Device info:emulator
Build info:emulator 5.0.0.36(SP1DEVC00E36R4P11log)
Fingerprint:9a7a625fe04bd5585d59ccd743ecae5659a88160429be94bc73c89cca57e4149
Module name:（这是我们的包名，请忽略）
Version:1.0.0
VersionCode:1000000
PreInstalled:No
Foreground:Yes
Pid:12515
Uid:20020050
Reason:TypeError
Error name:TypeError
Error message:is not callable
Stacktrace:
Cannot get SourceMap info, dump raw stack:
    at defaultMMKV (entry|@tencent/mmkv|1.3.9|src/main/ets/utils/MMKV.ts:47:1)
    at userId (entry|user|1.0.0|src/main/ets/user/j4.ts:64:1)
    at d110 (entry|contacts|1.0.0|src/main/ets/m5/m6.ts:14:1)
    at func_main_0 (entry|contacts|1.0.0|src/main/ets/m5/m6.ts:37:1)

```
Harmonry Next API12 Beta3版本 debug模式下使用正常，release模式下APP启动闪退。FaultLog日志如上所示，请帮忙查看一下，非常感谢

**Comment by lingol** [comment]
Now how do you solve this problem, in the end you need obfuscation right?

**Comment by limuyang2** [comment]
你怎么处理的混淆？

**Comment by tanranran** [comment]
+1。请问如何处理混淆导致的问题

**Comment by zhouqj1414657557** [comment]
同问

**Comment by sunwen0402** [comment]
我昨天也遇到了同样的问题, 排查到大半夜,还好来着看了眼

**Comment by Er3c** [comment]
> A beta version that fix this problem has been released in the ohpm, v2.0.0-SNAPSHOT.
why it still crached in v2.0.0-SNAPSHOT? what should I do anything else?
![image](https://github.com/user-attachments/assets/833881a9-ffd6-47f3-aa65-62c0b4610b08)

**Comment by lingol** [comment]
I have tried both turning on & off the obfuscation switch of the MMKV module, but both are not working for Apps that download MMKV from the OHPM.

I guess you guys will have to manually copy and paste the obfuscation configuration from MMKV.

**Comment by bluesky0506** [comment]
等待官方回复吧，我把混淆都去掉了。

**Comment by TheLittleBoy** [comment]
从ohpm下载 v2.0.0-beta1 版本，尝试后依然闪退。
目前解决办法是在主项目的混淆文件中增加配置项：

-keep-property-name
getDefaultMMKV

我这试了axios网络请求也会受到混淆的影响，有啥解决办法不？

**Comment by lingol** [comment]
v2.0.0 just released with support obfuscation. 
For the time being, you will have to manually copy the content of MMKV's [consumer-rules.txt](https://github.com/Tencent/MMKV/blob/master/OpenHarmony/MMKV/consumer-rules.txt) into your App's obfuscation-rules.txt.

**Comment by lingol** [comment]
It's fully supported in [v2.0.2](https://github.com/Tencent/MMKV/releases/tag/v2.0.2).
