### ISSUE TITLE
鸿蒙的有混淆规则吗？没找到

### ISSUE THREAD

**Issue by yongminghuang** [Tencent/MMKV#1397]
如题，鸿蒙配置如下混淆规则，
-enable-property-obfuscation
-enable-toplevel-obfuscation
-enable-filename-obfuscation
 -enable-export-obfuscation
运行报错
Stacktrace:
Cannot get SourceMap info, dump raw stack:
at defaultMMKV (entry|@tencent/mmkv|1.3.9|src/main/ets/utils/MMKV.ts:47:1)
at m103 (entry|entry|1.0.0|src/main/ets/k/l.ts:7:1)
at func_main_0 (entry|entry|1.0.0|src/main/ets/k/l.ts:160:1)

**Comment by lingol** [comment]
#1385
