### ISSUE TITLE
[Exception] flutter 2.0.1 exception in isolate

### ISSUE THREAD

**Issue by yoferzhang** [Tencent/MMKV#1411]
### The language of MMKV

> flutter 3.19.6

### The version of MMKV
 v2.0.1

### The platform of MMKV

>  iOS

### The installation of MMKV

>  Cocoapods

### What's the issue?

```
[E][IsolateRunner][ :0,  ][[_spawn] listen, applicationResult exception, Null check operator used on a null value
#0      _mmkvPlatform (package:mmkv/mmkv.dart:810:69)
#1      _mmkvPlatform (package:mmkv/mmkv.dart)
#2      _getMMKVWithID (package:mmkv/mmkv.dart:813:5)
#3      _getMMKVWithID (package:mmkv/mmkv.dart)
#4      new MMKV (package:mmkv/mmkv.dart:217:17)
#5      AlloyDatabaseManager.mmkv (package:alloy_report/src/alloy_database_manager.dart:9:28)
#6      AlloyDatabaseManager.mmkv (package:alloy_report/src/alloy_database_manager.dart)
#7      AlloyCacheManager.reportAll (package:alloy_report/src/alloy_cache_manager.dart:35:43)
#8      IsolateRunner._spawn.<anonymous closure>.<anonymous closure> (package:IsolateRunner/IsolateRunner.dart:137:33)
#9      _rootRun (dart:async/zone.dart:1399:13)
#10     _CustomZone.run (dart:async/zone.dart:1301:19)
#11     _runZoned (dart:async/zone.dart:1804:10)
#12     runZonedGuarded (dart:async/zone.dart:1792:12)
#13     IsolateRunner._spawn.<anonymous closure> (package:IsolateRunner/IsolateRunner.dart:136:7)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#17     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#18     _StreamController._add (dart:async/stream_controller.dart:658:7)
#19     _StreamController.add (dart:async/stream_controller.dart:606:5)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
Please provide the logs from MMKV.

**Comment by lingol** [comment]
The exception is on this line: https://github.com/Tencent/MMKV/blob/master/flutter/mmkv/lib/mmkv.dart#L810
```dart
final MMKVPluginPlatform _mmkvPlatform = MMKVPluginPlatform.instance!;
```
Looks like your MMKV plugin for the current platform iOS, aka [mmkv_ios](https://github.com/Tencent/MMKV/blob/master/flutter/mmkv/pubspec.yaml#L15), is not installed correctly.
