### ISSUE TITLE
Android 1.3.9 upgrading to 2.0.0  "libmmkv.so" not found

### ISSUE THREAD

**Issue by jameschenaime** [Tencent/MMKV#1421]
## Note:
The same phone (armeabi-v7a, Android 13) crashed after upgrading mmkv android sdk 1.3.9 to 2.0.0

### The language of MMKV

> Kotlin

### The version of MMKV

> v2.0.0

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?
> Crash

### What's the log of MMKV when that happened?
```
FATAL EXCEPTION: main (Ask Gemini)
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1765)
	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
	at com.xxx.zzz.init(zzz.java:39)
	at com.xxx.MyApplication.onCreate(MyApplication.kt:50)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7619)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by jameschenaime** [comment]
I see "And armv7 is droped from (v1.3.5~v1.3.6) v2.0+", the issue can be closed.
