### ISSUE TITLE
小米v7a的手机上运行闪退,是不是没有armeabi-v7a的libmmkv.so?

### ISSUE THREAD

**Issue by hockgod520** [Tencent/MMKV#1457]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Kotlin/Android

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

V2.0.1

### The platform of MMKV

> e.g. iOS or Android
Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone
maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

Shutting down VM
 com.pengpeng.avocado                 E  FATAL EXCEPTION: main
Process: com.pengpeng.avocado, PID: 30939
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
at java.lang.System.loadLibrary(System.java:1664)
at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:2)
at com.tencent.mmkv.MMKV.initialize(MMKV.java:24)
at com.tencent.mmkv.MMKV.initialize(MMKV.java:12)
at com.pengpeng.avocado.BaseApplication.g(BaseApplication.java:19)
at com.lefu.base.LefuApplication.onCreate(LefuApplication.java:4)
at com.pengpeng.avocado.BaseApplication.onCreate(BaseApplication.java:5)
at com.SecShell.SecShell.AW.onCreate(Unknown Source:29)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1191)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7052)
at android.app.ActivityThread.access$1700(ActivityThread.java:263)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8097)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

小米v8a的手机上运行闪退,是不是没有v8a的libmmkv.so

```[tasklist]
### Tasks
```

**Comment by hockgod520** [comment]
前面写错了,应该是armeabi-v7a架构的手机

**Comment by lingol** [comment]
#1445
