### ISSUE TITLE
LogServer.java  occurred   NullPointerException

### ISSUE THREAD

**Issue by caoxingyu** [Tencent/MMKV#211]
### The language of MMKV

> Java

### The version of MMKV

>  v1.0.17

### The platform of MMKV

>  Android

### The installation of MMKV

> Maven

### What's the issue?
  

> Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String 
 java.lang.CharSequence.toString()' on a null object reference
        at com.tencent.qcloud.logutils.LogServer.onActivityStarted(LogServer.java:58)
        at android.app.Application.dispatchActivityStarted(Application.java:214)
>Exception on LogServer.java : String content = item.getText().toString().trim();
item is is a null object

**Comment by caoxingyu** [comment]
qcloud issue
