### ISSUE TITLE
java.lang.UnsatisfiedLinkError: "/data/app/xxxx/lib/arm64/libmmkv.so" is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by javaeryang** [Tencent/MMKV#237]
04-08 11:27:02.822 28453-28453/? E/xxxx: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/xxxx/lib/arm64/libmmkv.so" is 64-bit instead of 32-bit
        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:85)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:72)
        at com.xxxx.Setting$2.Method(Setting.java:106)
        at com.xxxxUI.onCreate()
        at android.app.Activity.performCreate(Activity.java:6751)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2660)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2768)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4581)
        at android.app.ActivityThread.-wrap19(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6252)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by lingol** [comment]
You are packaging a wrong ABI library of MMKV in your apk. Looks like your apk(or some of your apk's other libs) is 32-bit only, and you packaged a 64-bit of libmmkv.so inside.

Google it and try to solve it yourself. https://groups.google.com/forum/#!topic/android-ndk/4nnvINgEKNM
