### ISSUE TITLE
still  has  java.lang.UnsatisfiedLinkError even after using ReLinker

### ISSUE THREAD

**Issue by longerian** [Tencent/MMKV#247]
### The language of MMKV

> Java

### The version of MMKV

> com.tencent:mmkv-static:1.0.15

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### Model

名称 | 占比 | 值
-- | -- | --
HUAWEI MLA-AL00 | 1 | 7

### System

名称 | 占比 | 值
-- | -- | --
6.0 | 1 | 7

### What's the issue?

> Post the outputs or screenshots for errors.

```
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/user/0/xxx/app_lib/libmmkv.so": -2
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4849)
	at android.app.ActivityThread.access$1600(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/user/0/xxx/app_lib/libmmkv.so": -2
	at xxx.onCreate(XXXApplication.java:368)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
	... 8 more
Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/user/0/xxx/app_lib/libmmkv.so": -2
	at java.lang.Runtime.load(Runtime.java:344)
	at java.lang.System.load(System.java:1079)
	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
```

> 
> Explain what you want by example or code **in English**.

```
            try {
                MMKV.initialize(Globals.getApplication());
            } catch (UnsatisfiedLinkError error) {
                error.printStackTrace();
                ReLinker.loadLibrary(Globals.getApplication(), "mmkv");
                MMKV.initialize(Globals.getApplication());
            }

```

**Comment by lingol** [comment]
```C
    static const char *clsName = "com/tencent/mmkv/MMKV";
    jclass instance = env->FindClass(clsName);
    if (!instance) {
        MMKVError("fail to locate class: %s", clsName);
        return -2;
    }
```
JNI_OnLoad returns -2 on failure of locating class `MMKV` in Java. Looks like you have mistakenly obscured MMKV's symbol.

**Comment by longerian** [comment]
Thanks, let me check it.
