### ISSUE TITLE
too small to be an ELF executable: only found 0 bytes

### ISSUE THREAD

**Issue by lycool** [Tencent/MMKV#315]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

com.tencent:mmkv-static:1.0.22

### The platform of MMKV

>  Android

### The installation of MMKV

>  Maven

### What's the issue?

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/xxx/lib/arm/libmmkv.so" is too small to be an ELF executable: only found 0 bytes

java.lang.UnsatisfiedLinkError happened only on Android OS 5.1 and below.

java.lang.RuntimeException: Unable to create application  java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/xxx/lib/arm/libmmkv.so" is too small to be an ELF executable: only found 0 bytes
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5087)
	at android.app.ActivityThread.access$1700(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5958)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/xxx/lib/arm/libmmkv.so" is too small to be an ELF executable: only found 0 bytes
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:988)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:85)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:68)

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/FAQ
