### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by qiaoshouqing** [Tencent/MMKV#340]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
Java

### The version of MMKV

> e.g. v1.0.10
v1.0.22

### The platform of MMKV

> e.g. iOS or Android
Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

**stack traces**
```

#00 pc 0000000000005fa4 /data/app/com.oppo.book-2/lib/arm64/libmmkv.so [arm64-v8a]
--
2 #01 pc 0000000000005c9c /data/app/com.oppo.book-2/lib/arm64/libmmkv.so [arm64-v8a]
3 java:
4 com.tencent.mmkv.MMKV.com.tencent.mmkv.MMKV mmkvWithID(java.lang.String,int)(MMKV.java:64)
```

**symbolize stack traces:**
```
std::__ndk1::__libcpp_deallocate(void*)
/Users/lingol/Library/Android/sdk/android-ndk-r16b/sources/cxx-stl/llvm-lib
nclude/new:234
MmapedFile::isFileValid()
/Users/lingol/Developer/mmkv/Android/MMKV/mmkv/src/main/cpp/MmapedFile.h:62
```

**log:**
```
09-07 15:59:36.888 21357 21357 E MMKV : fail to open:/data/user/0/com.oppo.book/files/mmkv/rdm_data.crc, No such file or directory
--
09-07 15:59:36.888 21357 21357 E MMKV : fail to lock fd=-1, ret=-1, error:Bad file descriptor
```

**Comment by lingol** [comment]
The symbolized stack trace doesn't make sense.

**Comment by lingol** [comment]
Please provide as **much** stack traces as possible, and as **much** logs as possible.

**Comment by qiaoshouqing** [comment]
This is all stack trace，all of SIGSEGV(SEGV_MAPERR)  crash only has two line native stack trace.But I find another log about SIGSEGV(SEGV_MAPERR)  crash.

**log**
```

09-03 23:29:40.418 27105 27138 E MMKV : fail to open:/data/user/0/com.oppo.book/files/mmkv/SKIN_SETTING.crc, Read-only file system
--
7709-03 23:29:40.418 27105 27138 E MMKV : fail to lock fd=-1, ret=-1, error:Bad file descriptor
```
Below is all log.
```
007:10.754 11260 11260 I MMKV : loading [SETTING] with 4606 size in total, file size is 8192
--
108-30 00:07:10.754 11260 11260 I MMKV : loading [SETTING] with crc 1856758840 sequence 3
208-30 00:07:10.755 11260 11260 I MMKV : loaded [SETTING] with 77 values
308-30 00:07:10.777 11260 11260 I MMKV : loading [LOGIN] with 2447 size in total, file size is 4096
408-30 00:07:10.777 11260 11260 I MMKV : loading [LOGIN] with crc 2825124434 sequence 2
508-30 00:07:10.778 11260 11260 I MMKV : loaded [LOGIN] with 15 values
608-30 00:07:10.795 11260 11260 W System.err: java.io.FileNotFoundException: /sdcard/OppoBook/acc.db: open failed: ENOENT (No such file or directory)
708-30 00:07:10.795 11260 11260 W System.err: at libcore.io.IoBridge.open(IoBridge.java:452)
808-30 00:07:10.795 11260 11260 W System.err: at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
908-30 00:07:10.795 11260 11260 W System.err: at com.qq.reader.common.b.c.a(AccountSwitchHandler.java:189)
1008-30 00:07:10.795 11260 11260 W System.err: at com.qq.reader.common.login.a.a.b(LoginConfig.java:113)
1108-30 00:07:10.795 11260 11260 W System.err: at com.qq.reader.AbsReaderApplication.a(AbsReaderApplication.java:207)
1208-30 00:07:10.795 11260 11260 W System.err: at com.qq.reader.AbsReaderApplication.a(AbsReaderApplication.java:225)
1308-30 00:07:10.795 11260 11260 W System.err: at com.qq.reader.AbsReaderApplication.onCreate(AbsReaderApplication.java:200)
1408-30 00:07:10.795 11260 11260 W System.err: at com.qq.reader.ReaderApplication.onCreate(ReaderApplication.java:34)
1508-30 00:07:10.795 11260 11260 W System.err: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
1608-30 00:07:10.795 11260 11260 W System.err: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)
1708-30 00:07:10.795 11260 11260 W System.err: at android.app.ActivityThread.access$1800(ActivityThread.java:170)
1808-30 00:07:10.795 11260 11260 W System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
1908-30 00:07:10.795 11260 11260 W System.err: at android.os.Handler.dispatchMessage(Handler.java:102)
2008-30 00:07:10.795 11260 11260 W System.err: at android.os.Looper.loop(Looper.java:179)
2108-30 00:07:10.795 11260 11260 W System.err: at android.app.ActivityThread.main(ActivityThread.java:5769)
2208-30 00:07:10.795 11260 11260 W System.err: at java.lang.reflect.Method.invoke(Native Method)
2308-30 00:07:10.795 11260 11260 W System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
2408-30 00:07:10.795 11260 11260 W System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
2508-30 00:07:10.796 11260 11260 W System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
2608-30 00:07:10.796 11260 11260 W System.err: at libcore.io.Posix.open(Native Method)
2708-30 00:07:10.796 11260 11260 W System.err: at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
2808-30 00:07:10.796 11260 11260 W System.err: at libcore.io.IoBridge.open(IoBridge.java:438)
2908-30 00:07:10.796 11260 11260 W System.err: ... 17 more
3008-30 00:07:10.945 11260 11260 E beacon : isModuleAble:not init ua
3108-30 00:07:10.953 11260 11260 D cmn_log : set LogInitParams=LogInitParams{iLog=com.oppo.cmn.a.f.c@ebb786c, debug=true, printFile=false, asyncPrint=true, filePath='null', baseTag='mob_ad'}
3208-30 00:07:10.968 11260 11260 D cmn_log : isHideDebugOpen=false
3308-30 00:07:10.972 11260 11260 D mob_ad : [ThreadPoolTool][11260][main:1]:set ThreadPoolParams=ThreadPoolParams{netExecutorService=java.util.concurrent.ThreadPoolExecutor@18972ca[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], ioExecutorService=java.util.concurrent.ThreadPoolExecutor@abb9c3b[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], bizExecutorService=java.util.concurrent.ThreadPoolExecutor@c1daf58[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], dlExecutorService=java.util.concurrent.ThreadPoolExecutor@a20a8b1[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], singleExecutorService=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@d33f196, scheduleExecutorService=java.util.concurrent.ScheduledThreadPoolExecutor@2bdc117[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]}
3408-30 00:07:10.978 11260 11260 D mob_ad : [Utils][11260][main:1]:setUseOtherModels=false
3508-30 00:07:10.978 11260 11260 D InterMobAdManager: initSdkSettings
3608-30 00:07:10.978 11260 11260 D mob_ad : [Utils][11260][main:1]:setAppId=3034874
3708-30 00:07:10.995 11260 11260 D mob_ad : [PkgMgrTool][11260][main:1]:checkCallingOrSelfPermission pmName=android.permission.ACCESS_NETWORK_STATE,result=true
3808-30 00:07:10.996 11260 11260 D mob_ad : [PkgMgrTool][11260][main:1]:checkCallingOrSelfPermission pmName=android.permission.ACCESS_WIFI_STATE,result=true
3908-30 00:07:10.996 11260 11260 D mob_ad : [PkgMgrTool][11260][main:1]:checkCallingOrSelfPermission pmName=android.permission.INTERNET,result=true
4008-30 00:07:10.996 11260 11260 D mob_ad : [PkgMgrTool][11260][main:1]:checkCallingOrSelfPermission pmName=android.permission.READ_PHONE_STATE,result=true
4108-30 00:07:10.997 11260 11260 D mob_ad : [PkgMgrTool][11260][main:1]:checkCallingOrSelfPermission pmName=android.permission.WRITE_EXTERNAL_STORAGE,result=true
4208-30 00:07:10.999 11260 11260 D mob_ad : [PkgMgrTool][11260][main:1]:isActivityExists intent=Intent { cmp=com.oppo.book/com.oppo.mobad.activity.AdActivity },result=true
4308-30 00:07:11.000 11260 11260 D mob_ad : [PkgMgrTool][11260][main:1]:isServiceExists intent=Intent { cmp=com.oppo.book/com.oppo.mobad.service.AdService },result=true
4408-30 00:07:11.000 11260 11260 D mob_ad : [InterMobAdManager][11260][main:1]:init sdk success.
4508-30 00:07:11.000 11260 11260 D acs_st : ACS_STmain:STManager : init start.
4608-30 00:07:11.001 11260 11260 D acs_common: ACS_COMMON main:ThreadPoolEngine : init ThreadPoolEngine
4708-30 00:07:11.001 11260 11260 D acs_common: ACS_COMMON main:ThreadPoolEngine : mExecutorService=null,initThreadPoolWithDefault
4808-30 00:07:11.001 11260 11260 D acs_common: ACS_COMMON main:MyThreadFactory : newThread thread name=acs_thread_1
4908-30 00:07:11.003 11260 11260 D acs_common: ACS_COMMON main:MyThreadFactory : newThread thread name=acs_thread_2
5008-30 00:07:11.004 11260 11260 D acs_st : ACS_STmain:STManager : has no initted.init!!!
5108-30 00:07:11.004 11260 11260 D acs_common: ACS_COMMON main:MyThreadFactory : newThread thread name=acs_thread_3
5208-30 00:07:11.005 11260 11260 D mob_ad : [LocationTool][11260][main:1]:register
5308-30 00:07:11.009 11260 11260 D mob_ad : [LocationTool][11260][main:1]:isGpsProviderEnabled =false
5408-30 00:07:11.010 11260 11260 D mob_ad : [LocationTool][11260][main:1]:isNetProviderEnabled =false
5508-30 00:07:11.010 11260 11260 D mob_ad : [LocationTool][11260][main:1]:isPassiveProviderEnabled =true
5608-30 00:07:11.011 11260 11260 W mob_ad : [LocationTool][11260][main:1]:don't have the permissions:ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION !!!
5708-30 00:07:11.011 11260 11260 D mob_ad : [Utils][11260][main:1]:setSdkInitSuccess
5808-30 00:07:11.011 11260 11260 D mob_ad : [IInitListener][11260][main:1]:init success.
5908-30 00:07:11.014 11260 11260 D mob_ad : [PkgInstallMgr][11260][main:1]:init
6008-30 00:07:11.014 11260 11260 D mob_ad : [PkgInstallMgr][11260][main:1]:init sAdItemDataMap
6108-30 00:07:11.014 11260 11260 D mob_ad : [PkgInstallMgr][11260][main:1]:init sInterBaseAdMap
6208-30 00:07:11.014 11260 11260 D mob_ad : [SystemBRMgr][11260][main:1]:register mHasRegistered=false
6308-30 00:07:11.018 11260 11260 D mob_ad : [SystemBRMgr][11260][main:1]:really register.
6408-30 00:07:11.019 11260 11260 E Demon : initAdvSdk pid= 11260
6508-30 00:07:11.026 11260 11322 D acs_st : ACS_STacs_thread_2:h : readFromFile
6608-30 00:07:11.028 11260 11322 D acs_st : ACS_STacs_thread_2:h : File Content:[]
6708-30 00:07:11.028 11260 11322 D acs_st : ACS_STacs_thread_2:h : init() errorString = []
6808-30 00:07:11.047 11260 11321 D acs_st : ACS_STacs_thread_1:SPUtil : startReportTimer=false
6908-30 00:07:11.047 11260 11321 D acs_st : ACS_STacs_thread_1:k : setReportTimer=false
7008-30 00:07:11.047 11260 11321 E acs_st : ACS_STacs_thread_1:lshxjtu : init startReportTimer now!!!
7108-30 00:07:11.048 11260 11321 D acs_st : ACS_STacs_thread_1:k : startReportTimer=false
7208-30 00:07:11.048 11260 11321 E acs_st : ACS_STacs_thread_1:lshxjtu : startReportTimer receive,reportTimer=null,startReportTimer=false,isStartTimering=false
7308-30 00:07:11.048 11260 11321 D acs_st : ACS_STacs_thread_1:k : startReportTimer=false
7408-30 00:07:11.048 11260 11325 D mob_ad : [FileTool][11260][cmn_single_1:267]:isSdCardAvailable=false
7508-30 00:07:11.049 11260 11323 D acs_st : ACS_STacs_thread_3:STManager : isStFileExists=true,ntLimit=30,lastTime=1567093895411,nowTime=1567094831049
7608-30 00:07:11.049 11260 11323 D acs_st : ACS_STacs_thread_3:STManager : needUpdateStConfigs=false
7708-30 00:07:11.049 11260 11323 D acs_st : ACS_STacs_thread_3:STManager : don't need update st configs.
7808-30 00:07:11.051 11260 11325 D mob_ad : [FileTool][11260][cmn_single_1:267]:getSdCardRootPath=/sdcard
7908-30 00:07:11.052 11260 11325 D mob_ad : [FileTool][11260][cmn_single_1:267]:isFileExists /sdcard/.mob_ad/.material/.video =false
8008-30 00:07:11.052 11260 11325 D mob_ad : [FileTool][11260][cmn_single_1:267]:getFileSize file=/sdcard/.mob_ad/.material/.video,size=0
8108-30 00:07:11.052 11260 11325 D mob_ad : [FileTool][11260][cmn_single_1:267]:getFolderOrFileSize filePath=/sdcard/.mob_ad/.material/.video,size=0
8208-30 00:07:11.052 11260 11325 D mob_ad : [FileTool][11260][cmn_single_1:267]:getFolderOrFileSize filePath=/sdcard/.mob_ad/.material/.video,size=0
8308-30 00:07:11.052 11260 11325 D mob_ad : [VideoCacheUtils][11260][cmn_single_1:267]:getVideoCacheSize=0
8408-30 00:07:11.054 11260 11325 D mob_ad : [FileTool][11260][cmn_single_1:267]:getSdCardRootPath=/sdcard
8508-30 00:07:11.055 11260 11325 D mob_ad : [Utils][11260][cmn_single_1:267]:getFolderFilesCount folderFile=/sdcard/.mob_ad/.material/.video,count=0
8608-30 00:07:11.055 11260 11325 D mob_ad : [VideoCacheUtils][11260][cmn_single_1:267]:getVideoCacheFilesCount=0
8708-30 00:07:11.055 11260 11325 D mob_ad : [InterMobAdManager][11260][cmn_single_1:267]:video cache size not over max size or over max count,don't need clear video cache.
8808-30 00:07:11.055 11260 11325 D mob_ad : [InterMobAdManager][11260][cmn_single_1:267]:startClearRewardSP
8908-30 00:07:11.057 11260 11325 D mob_ad : [SPEngine][11260][cmn_single_1:267]:context.getSharedPreferences name=com.oppo.mobad.reward.prefs,mode=0
9008-30 00:07:11.065 11260 11325 D mob_ad : [SPEngine][11260][cmn_single_1:267]:getAll=0
9108-30 00:07:11.065 11260 11325 D mob_ad : [Utils][11260][cmn_single_1:267]:getAllRewardTime size=0
9208-30 00:07:11.142 11260 11260 D com.coloros.mcssdk---: MCS-->MessageParser--getMessageByIntent--type:4105
9308-30 00:07:11.168 11260 11260 D com.coloros.mcssdk---: MCS-->OnHandleIntent-message:type:4105,messageID:0,taskID:null,appPackage:com.oppo.book,appKey:RefJ2SHOmTUpxamnqYSIIqA1,appSecret:hARi2P9qfxq9JzbNPjfwTdzU,registerID:null,sdkVersion:null,command:12289,params:null,responseCode:0,content:CN_c42f6ce538f36a2403812694cf928de4
9408-30 00:07:11.168 11260 11260 D com.coloros.mcssdk---: MCS-->process--AppMessageProcessor--message:type:4105,messageID:0,taskID:null,appPackage:com.oppo.book,appKey:RefJ2SHOmTUpxamnqYSIIqA1,appSecret:hARi2P9qfxq9JzbNPjfwTdzU,registerID:null,sdkVersion:null,command:12289,params:null,responseCode:0,content:CN_c42f6ce538f36a2403812694cf928de4
9508-30 00:07:11.168 11260 11260 D com.coloros.mcssdk---: MCS-->process--SptMessageProcessor--message:type:4105,messageID:0,taskID:null,appPackage:com.oppo.book,appKey:RefJ2SHOmTUpxamnqYSIIqA1,appSecret:hARi2P9qfxq9JzbNPjfwTdzU,registerID:null,sdkVersion:null,command:12289,params:null,responseCode:0,content:CN_c42f6ce538f36a2403812694cf928de4
9608-30 00:07:11.169 11260 11260 D com.coloros.mcssdk---: MCS-->process--SptMessageProcessor--message:type:4105,messageID:0,taskID:null,appPackage:com.oppo.book,appKey:RefJ2SHOmTUpxamnqYSIIqA1,appSecret:hARi2P9qfxq9JzbNPjfwTdzU,registerID:null,sdkVersion:null,command:12289,params:null,responseCode:0,content:CN_c42f6ce538f36a2403812694cf928de4
9708-30 00:07:11.169 11260 11260 D PushService: processMessage--CommandMessage->type:4105,messageID:0,taskID:null,appPackage:com.oppo.book,appKey:RefJ2SHOmTUpxamnqYSIIqA1,appSecret:hARi2P9qfxq9JzbNPjfwTdzU,registerID:null,sdkVersion:null,command:12289,params:null,responseCode:0,content:CN_c42f6ce538f36a2403812694cf928de4
9808-30 00:07:11.212 11260 11316 I QuestMobile: QuestMobile SDK init finish in process: com.oppo.book cost:41 毫秒
9908-30 00:07:11.234 11260 11316 E SQLiteLog: (14) cannot open file at line 31282 of [5a3022e081]
10008-30 00:07:11.234 11260 11316 E SQLiteLog: (14) os_unix.c:31282: (2) open(/sdcard/OppoBook/skin/skinlist.db) -
10108-30 00:07:11.237 11260 11316 E SQLiteDatabase: Failed to open database '/sdcard/OppoBook/skin/skinlist.db'.
10208-30 00:07:11.237 11260 11316 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
10308-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
10408-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
10508-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
10608-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
10708-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
10808-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
10908-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
11008-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
11108-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
11208-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
11308-30 00:07:11.237 11260 11316 E SQLiteDatabase: at com.qq.reader.core.b.a.a(SDSQLiteOpenHelper.java:144)
11408-30 00:07:11.237 11260 11316 E SQLiteDatabase: at com.qq.reader.plugin.skin.g.d(SkinDatebaseHandle.java:119)
11508-30 00:07:11.237 11260 11316 E SQLiteDatabase: at com.qq.reader.plugin.skin.h.i(SkinManager.java:278)
11608-30 00:07:11.237 11260 11316 E SQLiteDatabase: at com.qq.reader.plugin.skin.h.<init>(SkinManager.java:138)
11708-30 00:07:11.237 11260 11316 E SQLiteDatabase: at com.qq.reader.plugin.skin.h.b(SkinManager.java:120)
11808-30 00:07:11.237 11260 11316 E SQLiteDatabase: at com.qq.reader.AbsReaderApplication$4.run(AbsReaderApplication.java:298)
11908-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.os.Handler.handleCallback(Handler.java:739)
12008-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.os.Handler.dispatchMessage(Handler.java:95)
12108-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.os.Looper.loop(Looper.java:179)
12208-30 00:07:11.237 11260 11316 E SQLiteDatabase: at android.os.HandlerThread.run(HandlerThread.java:61)
12308-30 00:07:11.276 11260 11324 I DpmTcmClient: RegisterTcmMonitor from: org.apache.http.impl.conn.TcmIdleTimerMonitor
12408-30 00:07:11.337 11260 11260 D oppo_push: type:4105,messageID:0,taskID:null,appPackage:com.oppo.book,appKey:RefJ2SHOmTUpxamnqYSIIqA1,appSecret:hARi2P9qfxq9JzbNPjfwTdzU,registerID:null,sdkVersion:null,command:12289,params:null,responseCode:0,content:CN_c42f6ce538f36a2403812694cf928de4
12508-30 00:07:11.356 11260 11324 D libc-netbsd: [getaddrinfo]: hostname=oth.str.mdt.qq.com; servname=(null); app_uid=10091; ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0 from prox result 0
12608-30 00:07:11.357 11260 11324 I System.out: [socket] connection /183.232.94.121:8080;LocalPort=50970(30000)
12708-30 00:07:11.392 11260 11341 D libc-netbsd: [getaddrinfo]: hostname=coopmain.reader.qq.com; servname=(null); app_uid=10091; ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0 from prox result 0
12808-30 00:07:11.404 11260 11341 I System.out: [socket] connection coopmain.reader.qq.com/183.232.93.240:80;LocalPort=34663(10000)
12908-30 00:07:11.410 11260 11344 I DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
13008-30 00:07:11.418 11260 11344 I System.out: Not need to boost!
13108-30 00:07:11.434 11260 11344 D libc-netbsd: [getaddrinfo]: hostname=android.bugly.qq.com; servname=(null); app_uid=10091; ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0 from prox result 0
13208-30 00:07:11.434 11260 11344 I System.out: [socket] connection android.bugly.qq.com/121.51.23.159:80;LocalPort=53855(30000)
13308-30 00:07:11.452 11260 11337 D libc-netbsd: [getaddrinfo]: hostname=a.qchannel03.cn; servname=(null); app_uid=10091; ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0 from prox result 0
13408-30 00:07:11.452 11260 11337 I System.out: [socket] connection a.qchannel03.cn/124.243.193.144:443;LocalPort=58537(6000)
13508-30 00:07:11.821 11260 11316 W ResourceType: For resource 0x7f0604b2, entry index(1202) is beyond type entryCount(1202)
13608-30 00:07:11.821 11260 11316 W ResourceType: Failure getting entry for 0x7f0604b2 (t=5 e=1202) (error -75)
13708-30 00:07:11.822 11260 11316 E MMKV : fail to open:/data/user/0/com.oppo.book/files/mmkv/theme.crc, Read-only file system
13808-30 00:07:11.823 11260 11316 E MMKV : fail to lock fd=-1, ret=-1, error:Bad file descriptor
13908-30 00:07:11.846 11260 11316 E CrashReport-Native: Failed to open file /data/user/0/com.oppo.book/app_bugly/tomb_1567094831846.txt: Read-only file system
14008-30 00:07:11.846 11260 11316 E CrashReport-Native: write key fail
14108-30 00:07:11.846 11260 11316 E CrashReport-Native: Failed to record native log.
14208-30 00:07:11.846 11260 11316 E CrashReport-Native: write key fail
14308-30 00:07:11.846 11260 11316 E CrashReport-Native: Failed to record native log.
14408-30 00:07:11.846 11260 11316 E CrashReport-Native: write key fail
14508-30 00:07:11.846 11260 11316 E CrashReport-Native: Failed to record native log.
14608-30 00:07:11.846 11260 11316 E CrashReport-Native: write key fail
14708-30 00:07:11.846 11260 11316 E CrashReport-Native: Failed to record native log.
14808-30 00:07:11.846 11260 11316 E CrashReport-Native: write key fail
14908-30 00:07:11.846 11260 11316 E CrashReport-Native: Failed to record native log.
15008-30 00:07:11.846 11260 11316 E CrashReport-Native: write key fail
15108-30 00:07:11.846 11260 11316 E CrashReport-Native: Failed to record native log.
15208-30 00:07:11.846 11260 11316 E CrashReport-Native: write key fail
15308-30 00:07:11.847 11260 11316 E CrashReport-Native: Failed to record native log.
15408-30 00:07:11.847 11260 11316 E CrashReport-Native: write key fail
15508-30 00:07:11.847 11260 11316 E CrashReport-Native: Failed to record native log.
15608-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
15708-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
15808-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
15908-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
16008-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
16108-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
16208-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
16308-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
16408-30 00:07:11.944 11260 11316 E CrashReport-Native: Failed to record java thread name.
16508-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
16608-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
16708-30 00:07:11.944 11260 11316 E CrashReport-Native: write key fail
16808-30 00:07:11.944 11260 11316 E CrashReport-Native: Failed to record key-value list.
16908-30 00:07:11.946 11260 11316 E CrashReport-Native: write key fail
17008-30 00:07:11.946 11260 11316 E CrashReport-Native: Failed to record native log.


```

**Comment by lingol** [comment]
13708-30 00:07:11.822 11260 11316 E MMKV : fail to open:/data/user/0/com.oppo.book/files/mmkv/theme.crc, Read-only file system

There's something wrong with the file system.
