### ISSUE TITLE
云诊断上250+个因为找不到so包 crash

### ISSUE THREAD

**Issue by hytcooker2009** [Tencent/MMKV#376]
### The language of MMKV

> java

### The version of MMKV

>  api 'com.tencent:mmkv:1.0.23'

### The platform of MMKV

>  Android

### The installation of MMKV

> Maven

### What's the issue?

> java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.****.space-OSrY7iQtkxPEfoXOhymkrQ==/lib/arm/libc++_shared.so" has bad ELF magic
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1657)
	at com.tencent.mmkv.MMKV.a(SourceFile:1098)
	at com.***.space.core.BaseApplication.a(SourceFile:63)
	at com.***.space.ui.****SpaceApplication.a(SourceFile:105)
	at com.***.space.ui.****SpaceApplication.onCreate(SourceFile:88)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1124)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6004)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6783)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
 系统版本是8.1 这个只是一种一个 
      ndk {
            abiFilters "armeabi"
        }

**Comment by lingol** [comment]
Notice it's **libc++_shared.so** that's not correct. You are embedding the wrong libc++_shared.

**Comment by hytcooker2009** [comment]
is something wrong with "  abiFilters "armeabi" " in as ?

**Comment by hytcooker2009** [comment]
'com.tencent.mmkv-static:1.0.23'  can't complie

ERROR: Failed to resolve: com.tencent.mmkv-static:1.0.23:

**Comment by nacan** [comment]
> When it comes to libc++_shared.so, you just can't know for sure, it can be included by any libs.
> You can try different things though.
> Start with linking MMKV with 'com.tencent.mmkv-static:1.0.23' to avoid MMKV's dependence of libc++_shared.so.

Are you the author of 《第一行代码-Android》?

**Comment by lingol** [comment]
> > When it comes to libc++_shared.so, you just can't know for sure, it can be included by any libs.
> > You can try different things though.
> > Start with linking MMKV with 'com.tencent.mmkv-static:1.0.23' to avoid MMKV's dependence of libc++_shared.so.
> 
> Are you the author of 《第一行代码-Android》?

No. Why did you ask that?

**Comment by nacan** [comment]
> > > When it comes to libc++_shared.so, you just can't know for sure, it can be included by any libs.
> > > You can try different things though.
> > > Start with linking MMKV with 'com.tencent.mmkv-static:1.0.23' to avoid MMKV's dependence of libc++_shared.so.
> > 
> > 
> > Are you the author of 《第一行代码-Android》?
> 
> No. Why did you ask that?

Sorry，I misread your name

**Comment by lingol** [comment]
> @hytcooker2009 implementation 'com.tencent:mmkv-static:1.0.23'
> 
> > 'com.tencent.mmkv-static:1.0.23' can't complie
> > ERROR: Failed to resolve: com.tencent.mmkv-static:1.0.23:

@hytcooker2009 How did it go?
