### ISSUE TITLE
初始化mmkv时，偶尔会出现crash

### ISSUE THREAD

**Issue by jyh149129** [Tencent/MMKV#385]
系统：android 8.1.0 x86_64模拟器
mmkv版本：1.0.24
初始化代码：application中，通过 MMKV.initialize(this)初始化。
crash时控制台输出：
![捕获](https://user-images.githubusercontent.com/7726240/74588615-f3638e00-5038-11ea-92f2-e557f3845c35.PNG)

**Comment by jyh149129** [comment]
似乎图片没显示。
控制台输出如下：
 java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/cn.qjm.lpm-x1ORIxP868r6bvqXwYhmRQ==/lib/x86_64/libc++_shared.so" has bad ELF magic
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.tencent.mmkv.MMKV.a(MMKV.java:98)
        at com.tencent.mmkv.MMKV.a(MMKV.java:69)
        at cn.zjw.qjm.AppContext.onCreate(AppContext.java:101)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by lingol** [comment]
You’re packing the c++ library with wrong abi.
Try “com.tencent:mmkv-static:1.0.24”.
