### ISSUE TITLE
'libc++_shared.so has bad ELF magic' crash during initializing mmkv in mmkv-static lib

### ISSUE THREAD

**Issue by Pan-Gao** [Tencent/MMKV#401]
### The language of MMKV

> Java

### The version of MMKV

> com.tencent:mmkv-static:1.0.23

### The platform of MMKV

> Android

### The installation of MMKV

>  implementation 'com.tencent:mmkv-static:1.0.23'

### What's the issue?

>application crash while initializing.
At first, I got similar 'libc++_shared.so has bad ELF magic' crash, then I use mmkv-static lib to replace mmkv lib and the libc++_shared.so problem solved.
But the 'libmmkv.so has bad ELF magic' emerged.
Please give some advice! Thanks!

 java.lang.UnsatisfiedLinkError	dlopen failed: "/data/app/com.android.xxx-AGExd5eykUNZmPaKqar31w==/lib/arm/libmmkv.so" has bad ELF magic
Runtime.java	1016
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.xxx-AGExd5eykUNZmPaKqar31w==/lib/arm/libmmkv.so" has bad ELF magic
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1669)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:100)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:69)
	at com.android.xxx.utils.MMKVUtils.<clinit>(MMKVUtils.java:21)
	at com.android.xxx.utils.MMKVUtils.getSharedPreferences(MMKVUtils.java:37)
	at com.android.xxx.application.MusicApplication.initSharedPreferences(MusicApplication.java:428)
	at com.android.xxx.application.MusicApplication.onCreate(MusicApplication.java:256)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6211)
	at android.app.ActivityThread.access$1200(ActivityThread.java:236)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1851)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7053)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by lingol** [comment]
Google about 'bad ELF magic'. Looks like you have some problem with your IDE/packaging tools.

**Comment by guowuque** [comment]
@Pan-Gao  请问下这个问题有解决么
