### ISSUE TITLE
mmkv crashed

### ISSUE THREAD

**Issue by andyhaha** [Tencent/MMKV#460]
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
        at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xueqiu.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xueqiu.android-1/lib/arm, /data/app/com.xueqiu.android-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libmmkv.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:96)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:67)
        
the crash happened on ViVo X7plus，Andorid7.0, MMKV version is com.tencent:mmkv-static:1.1.1. help！

**Comment by lingol** [comment]
>couldn't find "libmmkv.so"

The log is pretty clear. Something is wrong with your pkg packaging or App installation/upgrade. 
You should check those possibilities. Nothing we can do here.
