### ISSUE TITLE
接入了MMKV之后,单元测试中so库缺失怎么办?

### ISSUE THREAD

**Issue by jiangkang** [Tencent/MMKV#507]
### The language of MMKV

Java and Kotlin

### The version of MMKV

latest version

### The platform of MMKV

Android

### The installation of MMKV

maven

### What's the issue?

项目进行**单元测试**的时候,报错:
```
com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.dylib'. Looked for: [armeabi-v7a], but only found: [].
	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:80)
```
 这是用了ReLinker之后的报错信息,不用Relinker也会提示 mmkv library找不到.
```
java.lang.UnsatisfiedLinkError: no mmkv in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:85)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:72)
```

### What's the log of MMKV when that happened?

 请问接入了MMKV之后,单元测试要怎么进行比较合适? 如果没有合适的建议,能提供一个libmmkv.dylib吗?

**Comment by lingol** [comment]
Something is wrong with your project. You are not integrating MMKV correctly. Your app should look for libmmkv.so, not libmmkv.dylib.

**Comment by jiangkang** [comment]
> Something is wrong with your project. You are not integrating MMKV correctly. Your app should look for libmmkv.so, not libmmkv.dylib.

my project integrates mmkv correctly, but it occurs error when i want to execute the unit test. "libmmkv.dylib" is MacOS platform when I use the relinker lib. if i don't use the relinker library, it still occurs error!
```

java.lang.UnsatisfiedLinkError: no mmkv in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:85)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:72)
```

**Comment by lingol** [comment]
Fix your unit test framework/tools then.

**Comment by jiangkang** [comment]
> Fix your unit test framework/tools then.

@lingol  OK,thanks! I will look for alternative way to solve the problem

**Comment by RitaLing** [comment]
java.lang.UnsatisfiedLinkError:
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1012)
  at java.lang.System.loadLibrary (System.java:1669)
  at com.tencent.mmkv.MMKV.initialize (MMKV.java:100)
  at com.tencent.mmkv.MMKV.initialize (MMKV.java:69)

**Comment by helloJude** [comment]
> > Something is wrong with your project. You are not integrating MMKV correctly. Your app should look for libmmkv.so, not libmmkv.dylib.
> > @lingol
> 
> my project integrates mmkv correctly, but it occurs error when i want to execute the unit test. "libmmkv.dylib" is MacOS platform when I use the relinker lib. if i don't use the relinker library, it still occurs error!
> 
> ```
> 
> java.lang.UnsatisfiedLinkError: no mmkv in java.library.path
> 
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
> 	at java.lang.System.loadLibrary(System.java:1124)
> 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:85)
> 	at com.tencent.mmkv.MMKV.initialize(MMKV.java:72)
> ```

嗨 我在写安卓单测也遇到了同样的问题，请问是如何解决的

**Comment by tomgreco** [comment]
> 嗨 我在写安卓单测也遇到了同样的问题，请问是如何解决的

There is no solution yet. Several people have this issue because there's no documentation on how to write unit tests using MMKV in an android project. 
And instead of providing solutions the developer @lingol just yells at people. Disgusting human.
