### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/mmkv/MMKV;

### ISSUE THREAD

**Issue by Mangosir** [Tencent/MMKV#567]
### The language of MMKV

> java

### The version of MMKV

>  v1.2.5

### The platform of MMKV

> Android

### What's the issue?

刚接入这个框架，在现有的应用里的application中调用MMKV.initialize(path);抛出错误，用的手机是xiaomi 8 se

### What's the log of MMKV when that happened?
`
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/mmkv/MMKV;

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mmkv.MMKV" on path: DexPathList[[zip file "/data/app/com.xbhz.box-uRvQNDamV8Y6n5mequd9cg==/base.apk"],nativeLibraryDirectories=[/data/app/com.xbhz.box-uRvQNDamV8Y6n5mequd9cg==/lib/arm64, /data/app/com.xbhz.box-uRvQNDamV8Y6n5mequd9cg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mango.support.preference.PreferenceUtil.initMMKV(PreferenceUtil.java:48)
 `

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/FAQ_cn

**Comment by Mangosir** [comment]
> https://github.com/Tencent/MMKV/wiki/FAQ_cn

 ReLinker 这个在提issue前就试过，同样是抛这个错

**Comment by lingol** [comment]
Did you find libmmkv.so inside your apk?

**Comment by Mangosir** [comment]
> Did you find libmmkv.so inside your apk?

在apk的lib目录里并没有这个so

**Comment by lingol** [comment]
Then it's not MMKV's problem. You should check your project configuration and find out why mmkv is not embeded.
