### ISSUE TITLE
Android8 后台静置重新初始化mmkv 加载不到libmmkv.so

### ISSUE THREAD

**Issue by AymerZhang** [Tencent/MMKV#570]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.
1.0.23

### The platform of MMKV

> e.g. iOS or Android
Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

BOARD=ALP
CPU_ABI2=
HOST=WUH1000128978
versionName=3.4.0.11261553
IS_TREBLE_ENABLED=true
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@c08574d
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=false
IS_USERDEBUG=false
DISPLAY=ALP-TL00 8.1.0.351(C01)
SUPPORTED_ABIS=[Ljava.lang.String;@cb4d202
FINGERPRINT=HUAWEI/ALP-TL00/HWALP:8.1.0/HUAWEIALP-TL00/351(C01):user/release-keys
PRODUCT=ALP-TL00
HIDE_PRODUCT_INFO=false
ID=HUAWEIALP-TL00
replacements=[Ljava.lang.String;@99f6d50
TYPE=user
SERIAL=NDF7N18103001899
NO_HOTA=false
IS_CONTAINER=false
IS_ENG=false
DEVICE=HWALP
TIME=1544242431000
IS_USER=true
MODEL=ALP-TL00
MANUFACTURER=HUAWEI
USER=test
versionCode=880
BRAND=HUAWEI
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@a8f6a77
matchers=[Ljava.lang.String;@863713
HARDWARE=kirin970
IS_DEBUGGABLE=false
BOOTLOADER=unknown
RADIO=unknown
TAG=Build
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:4)
	at android.os.Handler.handleCallback(Handler.java:809)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7383)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.chehejia.oc.m01-TBWDg7lrljgGQwQnlsmgcQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.chehejia.oc.m01-TBWDg7lrljgGQwQnlsmgcQ==/lib/arm64, /data/app/com.chehejia.oc.m01-TBWDg7lrljgGQwQnlsmgcQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libmmkv.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
	at java.lang.System.loadLibrary(System.java:1660)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:12)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:3)
	at com.chehejia.oc.m01.ble.model.BlePreferencesHelper.<init>(BlePreferencesHelper.java:23)
	at com.chehejia.oc.m01.view.gui.car.helper.VehicleHelper.getNewestVehicleStatus(VehicleHelper.java:5)
	at com.chehejia.oc.m01.view.gui.car.home.CarHomePresenter$1.onAmSucceed(CarHomePresenter.java:3)
	at com.chehejia.oc.m01.model.listener.M01RequestListener.onSucceed(M01RequestListener.java:4)
	at com.ampmind.apigetway.listener.RequestListener.onNext(RequestListener.java:7)
	at com.ampmind.apigetway.listener.RequestListener.onNext(RequestListener.java:1)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:2)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:8)
	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:1)
	... 7 more
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.chehejia.oc.m01-TBWDg7lrljgGQwQnlsmgcQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.chehejia.oc.m01-TBWDg7lrljgGQwQnlsmgcQ==/lib/arm64, /data/app/com.chehejia.oc.m01-TBWDg7lrljgGQwQnlsmgcQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libmmkv.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
	at java.lang.System.loadLibrary(System.java:1660)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:12)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:3)
	at com.chehejia.oc.m01.ble.model.BlePreferencesHelper.<init>(BlePreferencesHelper.java:23)
	at com.chehejia.oc.m01.view.gui.car.helper.VehicleHelper.getNewestVehicleStatus(VehicleHelper.java:5)
	at com.chehejia.oc.m01.view.gui.car.home.CarHomePresenter$1.onAmSucceed(CarHomePresenter.java:3)
	at com.chehejia.oc.m01.model.listener.M01RequestListener.onSucceed(M01RequestListener.java:4)
	at com.ampmind.apigetway.listener.RequestListener.onNext(RequestListener.java:7)
	at com.ampmind.apigetway.listener.RequestListener.onNext(RequestListener.java:1)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:2)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:8)
	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:1)
	at android.os.Handler.handleCallback(Handler.java:809)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7383)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

### What's the log of MMKV when that happened?
> Your detail logs. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.

**Comment by lingol** [comment]
**PLEASE** check the FAQ or Google about 'android jni java.lang.unsatisfiedlinkerror'.

**Comment by AymerZhang** [comment]
the .so file in your project and this bug is only Occasionally.

**Comment by yixi195** [comment]
这个怎么解决？ libmmkv.so 去哪里下载

**Comment by yixi195** [comment]
我也时常会在crash 后台看到这个错误，
