### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by 532922397** [Tencent/MMKV#592]
"main" prio=5 tid=2 RUNNABLE
Free memory 6MB
Total memory 168MB
Max memory 512MB
at com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
at com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:166)
...
at xx.xx.$ActivityLifeCycleListener.onActivityCreated(Application.kt:288)
at xx.xx.$Companion.activityCreatedCallback(LifeCallBackManager.kt:88)
at xx.xx.$Companion.access$activityCreatedCallback(LifeCallBackManager.kt:24)
at xx.xx.$Companion$sDefaultXXCallback$1.onActivityCreated(LifeCallBackManager.kt:278)
at android.app.Application.dispatchActivityCreated(Application.java:206)
at android.app.Activity.onCreate(Activity.java:1075)
at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:154)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
at android.app.Activity.performCreate(Activity.java:7259)
at android.app.Activity.performCreate(Activity.java:7250)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:667)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3053)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1772)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:197)
at android.app.ActivityThread.main(ActivityThread.java:7022)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

**Comment by lingol** [comment]
Maybe the reason is the device is running at a low memory? Do you have more cases?

**Comment by 532922397** [comment]
> 也许是由于设备内存不足而导致的？您还有更多案例吗？


No other cases have been found yet

**Comment by lingol** [comment]
Did you found any more cases now?

**Comment by 532922397** [comment]
Not recently

**Comment by 532922397** [comment]
> > 您现在收集了更多的案件吗？
> 
> [trace.txt](https://github.com/Tencent/MMKV/files/6538445/trace.txt)

**Comment by lingol** [comment]
I believe it's ANR due to GC.

**Comment by 532922397** [comment]
> 我相信这是AGC造成的。

哦，请问有什么好的办法规避吗？

**Comment by lingol** [comment]
You're using a bad translater. It's not AGC, it's GC, garbage collection.

**Comment by 532922397** [comment]
> You're using a bad translator. It's not AGC, it's GC, short for Garbage Collection.

Well, I see it's GC. Why does GC cause anr of mmkv? Can you give me some advice? thank you

**Comment by lingol** [comment]
It's GC cause Android ANR. Not MMKV's ANR. It has nothing to do with MMKV.
