### ISSUE TITLE
多进程使用MMKV，报Caused by: java.lang.IllegalStateException: 

### ISSUE THREAD

**Issue by fingdo** [Tencent/MMKV#619]
### The language of MMKV
Android ,java

### The version of MMKV
v1.2.4 

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?
在Application中调用MMKV.initialize(application)，在每个进程都有调用
然后在进入app的启动页使用MMKV.mmkvWithID获取mmkv，抛出异常，偶现

### What's the log of MMKV when that happened?
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2724)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2789)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1527)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:203)
  at android.app.ActivityThread.main (ActivityThread.java:6251)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)
Caused by: java.lang.IllegalStateException: 
  at com.tencent.mmkv.MMKV.mmkvWithID (MMKV.java:164)
```

**Comment by lingol** [comment]
You should check the exception reason for that crash. It will be crystal clear:
> "You should Call MMKV.initialize() first."

**Comment by billdizl** [comment]
> ### MMKV的语言
> 安卓,java
> 
> ### MMKV的版本
> v1.2.4
> 
> ### MMKV的平台
> 安卓
> 
> ### MMKV的安装
> 行家
> 
> ### 有什么问题？
> 在Application中调用MMKV.initialize(application)，在每次调用都有调用 然后在进入app的启动页使用MMKV.mmkvWithID获取mmkv，抛出异常，偶现
> 
> ### 发生这种情况时 MMKV 的日志是什么？
> ```
> java.lang.RuntimeException: 
>   at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2724)
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2789)
>   at android.app.ActivityThread.-wrap12 (ActivityThread.java)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1527)
>   at android.os.Handler.dispatchMessage (Handler.java:110)
>   at android.os.Looper.loop (Looper.java:203)
>   at android.app.ActivityThread.main (ActivityThread.java:6251)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)
> Caused by: java.lang.IllegalStateException: 
>   at com.tencent.mmkv.MMKV.mmkvWithID (MMKV.java:164)
> ```
大佬，你这个解决了吗？我也存在这个问题，但只在application中初始化了一次，在进入app的启动页使用MMKV.mmkvWithID获取mmkv，抛出异常，偶现（仅仅出现在低版本手机上）

**Comment by lingol** [comment]
You should check the exception reason for that crash. @billdizl

**Comment by billdizl** [comment]
> 

1. 首先我没有复现手机
2. 通过firebase查看到的崩溃信息:Caused by java.lang.IllegalStateException: You should Call MMKV.initialize() first.
       at com.tencent.mmkv.MMKV.defaultMMKV(MMKV.java:483)
       at com.xxx.xxx$Companion.getMMKV(MMKVUtils.kt:75)
       at com.xxx.xxx.MMKVUtils$Companion.decodeString(MMKVUtils.kt:60)
       at com.xxx.xxx.view.activity.LoginBtfeelActivity.initData(LoginBtfeelActivity.kt:554)
       at com.xxx.xxx.activity.LoginBtfeelActivity.onCreate(LoginBtfeelActivity.kt:173)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
出现的手机是在海外的8.1版本手机上出现的设备
品牌：LGE
型号：Nexus 5X
屏幕方向： 纵向
可用 RAM： 1.3 GB
可用磁盘空间： 386.2 MB
操作系统
版本：Android 8.1.0
屏幕方向： 纵向
是否已取得 root 权限：否
故无法准确定位是什么原因导致的
3.最主要是我在我们公司的所有手机上安装都正常运行,如果说是代码问题导致,我是参考文档使用的,application中进行
<img width="692" alt="image" src="https://user-images.githubusercontent.com/30317994/223004348-4b8012e3-3d2d-4b4e-9eb6-2e6d3e4d5155.png">
同时也排除了多次初始化MMKV.initialize的问题,在LoginBtfeelActivity也就是应用页面进行获取MMKV.defaultMMKV()时崩溃报
You should Call MMKV.initialize() first,难道 application中的MMKV.initialize方法 不优先于在应用界面的MMKV.defaultMMKV()方法执行吗?故,我真的找不到问题所在了,(我通过源码分析MMKV.rootDir==null时才报这个错,但是doInitialize()方法已经进行对MMKV.rootDir赋值,除非context.filesDir.absolutePath + "/mmkv"这个路径是空的才会导致报错崩溃,那么我该如何去解决呢?

**Comment by lingol** [comment]
Is your `Application.init()` called inside `Application.onCreate()`? If no, you should move the `MMKV.initialize()` into it.
https://github.com/Tencent/MMKV/wiki/android_tutorial

**Comment by billdizl** [comment]
是的 ,我是这么做的.
<img width="993" alt="image" src="https://user-images.githubusercontent.com/30317994/223011925-5e1a5493-95c1-4f41-b843-b00122e59f27.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/30317994/223011980-d5c6a927-ef97-4b16-87ea-79bb404dd2ca.png">
<img width="784" alt="image" src="https://user-images.githubusercontent.com/30317994/223012010-954c97c3-1b90-4f77-8294-ea506f00d345.png">
在application中初始化 仅仅一次

**Comment by billdizl** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/30317994/223012780-23fb0e19-c1de-4391-b590-b6d8ac8b0991.png">
<img width="364" alt="image" src="https://user-images.githubusercontent.com/30317994/223012829-564d2604-b507-4cdd-b7a8-7f8e070b5190.png">

**Comment by lingol** [comment]
Do you see any MMKV initialization logs in those crashed devices?

**Comment by billdizl** [comment]
没有, 1.我们没有该复现机器 (线上bug) 2.我们没有打印MMKV initialization logs 收集系统

**Comment by lingol** [comment]
1. You should turn on / collect MMKV's log. It helps.
2. When you said you don't print/collect MMKV's log, how about your own log such as this line of log?
<img width="384" alt="image" src="https://user-images.githubusercontent.com/2088859/223017183-89a2c303-d4d5-4929-b18a-4a36a62772bc.png">

**Comment by billdizl** [comment]
但是我没有复现机型,我怎么办?需要将log打开,并收集log日志?
