### ISSUE TITLE
dlopen failed: cannot locate symbol "_Unwind_Resume" referenced

### ISSUE THREAD

**Issue by whoislxy** [Tencent/MMKV#622]
Kotlin  v1.2.7 Android

依赖了mmkv，同时依赖的了别的库，都用了用了libc++_shared.so
 packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
去重复后，运行报错 
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/xxxxx-__4dUr7_JxfrGDUY9MLDIw==/lib/arm64/libmmkv.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:110)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:71)

**Comment by lingol** [comment]
Use mmkv-static, as we had recommended in the wiki.

**Comment by lingol** [comment]
Use mmkv-static, as we had recommended in the wiki.
