### ISSUE TITLE
Could not find 'libmmkv.so'

### ISSUE THREAD

**Issue by hejingzhou** [Tencent/MMKV#676]
### The language of MMKV
Kotlin

### The version of MMKV
一直保持"1.2.7"未变更过版本

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?
您好：
感谢开源
Android 10    HUAWEI LIO-AN00
Could not find 'libmmkv.so'
看了好多issue但是还是没有解决   希望大佬指点一下

Init:
```kotlin
 private fun initMMKV() {
        val dir = filesDir.absolutePath + "/mmkv"
        MMKV.initialize(
            dir
        ) { libName -> ReLinker.loadLibrary(this, libName) }
    }
```

Error Log:
```log
20182-20182/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kandayi.client, PID: 20182
    java.lang.RuntimeException: Unable to create application com.kandayi.client.KanDaYiApplication: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7409)
        at android.app.ActivityThread.access$2400(ActivityThread.java:251)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at com.kandayi.client.KanDaYiApplication$initMMKV$1.loadLibrary(KanDaYiApplication.kt:134)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:105)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:98)
        at com.kandayi.client.KanDaYiApplication.initMMKV(KanDaYiApplication.kt:132)
        at com.kandayi.client.KanDaYiApplication.onCreate(KanDaYiApplication.kt:61)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7393)
        at android.app.ActivityThread.access$2400(ActivityThread.java:251) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284) 
```

### What's the log of MMKV when that happened?
初始化

**Comment by hejingzhou** [comment]
之前使用没问题  但是后来不知道调整了什么就不行了

**Comment by lingol** [comment]
And I will how to repeat what has been said multiple times here:
CHECK YOUR PROJECT SETTINGS, AND CHECK YOUR APK FOR THAT libmmkv.so.

**Comment by Likeyong** [comment]
兄弟 你的问题解决了吗

**Comment by mysiga** [comment]
你是用.aab安装？

**Comment by knyou** [comment]
> 兄弟你的问题解决了吗

我这边遇到同样的问题，发现是在其他进程里也做了初始化MMKV的操作，后来改成只在主进程里初始化MMKV就没遇到了。你可以试下，如果你没有多进程的使用场景

**Comment by Allen-ZXJ** [comment]
我也遇到了，用aab安装，只加了v7和v8架构
