### ISSUE TITLE
MMKV crashed on NUBIA

### ISSUE THREAD

**Issue by zhangxiao-chn** [Tencent/MMKV#688]
### The language of MMKV

> Java\ Kotlin

### The version of MMKV

> v1.2.4   & v1.2.8

### The platform of MMKV

> Android

### The installation of MMKV

>  Maven

### What's the issue?

> crashed when MMKV init

### What's the log of MMKV when that happened?
    java.lang.UnsatisfiedLinkError: dlopen failed: library "ld-android.so" not found
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:119)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:108)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:75)
        at com.msb.music.common.utils.MMKVUtil.initMMKV(MMKVUtil.java:35)
        at com.msb.music.common.InitMMKVAndRxNet.initConfig(InitMMKVAndRxNet.java:27)
        at com.msb.music.ui.WelComeActivity.initSDK(WelComeActivity.java:164)
        at com.msb.music.ui.WelComeActivity.access$000(WelComeActivity.java:58)
        at com.msb.music.ui.WelComeActivity$1.handleMessage(WelComeActivity.java:82)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:5751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)

**Comment by lingol** [comment]
As far as I know, MMKV doesn't produce a product named **"ld-android.so",** nor does MMKV depend on it.
You should check your project for the answer.
