### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by LinMingkui** [Tencent/MMKV#705]
### The language of MMKV

Java

### The version of MMKV

1.2.8

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/com.friends.meeti-1/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libmmkv.so" segment 1: Permission denied
at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
at java.lang.System.loadLibrary(System.java:1657)
at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:121)
at com.tencent.mmkv.MMKV.initialize(MMKV.java:108)
at com.tencent.mmkv.MMKV.initialize(MMKV.java:71)
at com.friends.meeti.utils.MMKVUtil.<init>(MMKVUtil.java:71)
at com.friends.meeti.utils.MMKVUtil.<clinit>(MMKVUtil.java:17)
at com.friends.meeti.utils.MMKVUtil.get(MMKVUtil.java:76)
at com.friends.meeti.viewmodel.AppViewModel.<init>(AppViewModel.java:46)
at java.lang.Class.newInstance(Class.java)
at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
at com.lmk.architecture.utils.app.BaseApp.getApplicationScopeViewModel(BaseApp.java:42)
at com.friends.meeti.base.App.onCreate(App.java:59)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1126)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6074)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1778)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6958)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by lingol** [comment]
The error is as clear as crystal. Why do you still have to ask here?
>Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/com.friends.meeti-1/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libmmkv.so" segment 1: Permission denied

What you should do, is searching Google with keywords **java.lang.UnsatisfiedLinkError** & **Permission denied**.

**Comment by lingol** [comment]
For example, an **one-second search** and I got this https://github.com/android/ndk/issues/979

**Comment by LinMingkui** [comment]
> For example, an **one-second search** and I got this [android/ndk#979](https://github.com/android/ndk/issues/979)

I'm very sorry, I just searched the "UnsatisfiedLinkError" keyword in the issues before posting and it seems that I didn't find the same. I will pay attention next time. Thanks for your answer.
