### ISSUE TITLE
I got a java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by parcool** [Tencent/MMKV#715]
### The language of MMKV
> Kotlin
### The version of MMKV
> 1.2.9
### The platform of MMKV
> Android
### The installation of MMKV
> Maven

### What's the issue?
I got a OutOfMemoryError by using mmkv. here is my code.
#### crash log
```Shell
07-01 13:06:50.072 E/AndroidRuntime(27432): FATAL EXCEPTION: main
07-01 13:06:50.072 E/AndroidRuntime(27432): Process: com.parcool.tksl, PID: 27432
07-01 13:06:50.072 E/AndroidRuntime(27432): java.lang.OutOfMemoryError: Failed to allocate a 3825263632 byte allocation with 25165824 free bytes and 164MB until OOM, target footprint 53608816, growth limit 201326592
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at java.util.ArrayList.<init>(ArrayList.java:166)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.parcool.tksl.entity.AccountInfoEntity$Creator.createFromParcel(Unknown Source:78)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.parcool.tksl.entity.AccountInfoEntity$Creator.createFromParcel(Unknown Source:0)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.tencent.mmkv.MMKV.decodeParcelable(MMKV.java:573)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.tencent.mmkv.MMKV.decodeParcelable(MMKV.java:540)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.parcool.tksl.util.CommonUtil.getAccountInfoEntity(CommonUtil.kt:60)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.parcool.tksl.ui.activity.case.CaseDetailActivity$onCreate$1$2.invoke(CaseDetailActivity.kt:141)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.parcool.tksl.ui.activity.case.CaseDetailActivity$onCreate$1$2.invoke(CaseDetailActivity.kt:61)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2156)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2399)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2578)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:523)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2564)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2540)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:613)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:764)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:103)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:447)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:416)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at android.os.Handler.handleCallback(Handler.java:938)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at android.os.Looper.loop(Looper.java:223)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at java.lang.reflect.Method.invoke(Native Method)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-01 13:06:50.072 E/AndroidRuntime(27432): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

#### my code
```Kotlin
//application
class App : Application() {
    companion object {
        lateinit var kv: MMKV
    }

   override fun onCreate() {
        super.onCreate()
        initMMKV()
    }

    private fun initMMKV() {
        val rootDir: String = MMKV.initialize(this)
        kv = MMKV.defaultMMKV(1, "parcool")!!
    }
}

//util
object CommonUtil {
    fun getAccountInfoEntity(): AccountInfoEntity? {
        return App.kv.decodeParcelable("account_info_entity",AccountInfoEntity::class.java)
    }
}

//entity
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
@Parcelize
data class AccountInfoEntity(
    var access_token: String?,
    var flagSuper: Boolean?,
    var operatorCode: String,
    var operatorLogin: String,
    var operatorLoginAndOperatorName: String,
    var operatorName: String,
    var operatorType: String,
    var organizationId: String,
    var organizationName: String,
    var sysTrees: List<SysTreesEntity>,
    var roles: List<String>,
    var contractorCode: String?
) : Parcelable

@Parcelize
data class SysTreesEntity(
    var applicationCode: String,
    var childList: List<SysTreesEntity>,
    var choose: Boolean,
    var level: Int,
    var menuIcon: String,
    var order: Int,
    var permissionType: String,
    var rowId: Long,
    var tag: String,
    var treeDescription: String,
    var treeId: String,
    var treeName: String,
    var treePid: String?,
    var treeType: String,
    var treeUrl: String
) : Parcelable

//activity
...
@Composable
fun foo(){
 CommonUtil.getAccountInfoEntity()?.let { account ->
 ...
 }
}
...
```

I watched the `Android Profiler` and it does not show any memory leaks. the `java.lang.OutOfMemoryError ` just occurd sometimes.

**Comment by lingol** [comment]
And the logs of MMKV?

**Comment by lingol** [comment]
Well, you know what, I don't need the logs to see what wrong. 
It crashed inside `com.parcool.tksl.entity.AccountInfoEntity$Creator.createFromParcel( )`. So it must be the stored Parcel object being too big and the Android's Parcel library doesn't handle it well. 

Nothing to do with MMKV, as far as I care.

**Comment by parcool** [comment]
@lingol thanks your response. it seems `kotlinx.parcelize.Parcelize` make the bug.

**Comment by parcool** [comment]
There is new discoveries，I tested this code and get oom:
```
 //entity
import android.os.Parcelable
import kotlinx.parcelize.Parcelize
@Parcelize
data class AccountInfoEntity(
    var access_token: String?,
    var flagSuper: Boolean?,
    var operatorCode: String,
    var operatorLogin: String,
    var operatorLoginAndOperatorName: String,
    var operatorName: String,
    var operatorType: String,
    var organizationId: String,
    var organizationName: String,
    var sysTrees: List<SysTreesEntity>?,
    var roles: List<String>?,
    var contractorCode: String?
) : Parcelable

@Parcelize
data class SysTreesEntity(
    var applicationCode: String,
    var childList: List<SysTreesEntity>?,
    var choose: Boolean,
    var level: Int,
    var menuIcon: String,
    var order: Int,
    var permissionType: String,
    var rowId: Long,
    var tag: String,
    var treeDescription: String,
    var treeId: String,
    var treeName: String,
    var treePid: String?,
    var treeType: String,
    var treeUrl: String
) : Parcelable


    suspend fun test() {
        val jsonStr = "{\"code\":\"10000\",\"message\":\"查询成功\",\"requestId\":\"8c12e53c-ad48-4ace-aaae-9a9918241e8e\",\"result\":{\"rowId\":4,\"caseId\":\"CS1409321006093615104\",\"caseTime\":\"2021-06-01 09:21:04\",\"caseTypeId\":\"CTP1408341815982354432\",\"typeName\":\"测试类型\",\"operatorCode\":\"ACC1343468071999999999\",\"operatorName\":\"系统管理员\",\"operatorCodes\":\"[\\\"ACC1343468071999999999\\\",\\\"ACC1402122610949808128\\\"]\",\"operatorNames\":\"[\\\"系统管理员\\\",\\\"张小五\\\"]\",\"nowOperatorCodes\":\"[\\\"ACC1402122610949808128\\\"]\",\"nowOperatorNames\":\"[\\\"张小五\\\"]\",\"caseSource\":\"2\",\"riverId\":\"3\",\"riverCode\":\"测试河流2\",\"riverName\":\"测试河流2\",\"reportName\":\"xxxx\",\"reportPhone\":\"1864846468\",\"description\":\"重新找存在中\",\"flagRegister\":null,\"dealStatus\":\"2\",\"stage\":\"待业务科室处理\",\"deleteFlag\":\"0\",\"createTime\":\"2021-06-28 09:21:26\",\"createBy\":\"superadmin-超级管理员\",\"updateTime\":\"2021-06-28 23:25:44\",\"updateBy\":\"admin-系统管理员\",\"files\":[\"http://file.bokentech.cn/water/upload/cdn/2021/06/f4120d9e-e1b.png\"],\"approvalLogs\":[{\"rowId\":92,\"id\":\"AL1409533481309216768\",\"refNo\":\"CS1409321006093615104\",\"refType\":\"WATER_METHOD\",\"conclusion\":\"通过\",\"stage\":\"分管领导处理\",\"operating\":\"系统管理员-（分管领导）\",\"remarks\":\"快去处理哟\",\"jbr\":\"张小五\",\"flagRegister\":null,\"deleteFlag\":\"0\",\"createTime\":\"2021-06-28 23:25:44\",\"updateTime\":\"2021-06-28 23:25:40\",\"files\":[]},{\"rowId\":null,\"id\":null,\"refNo\":null,\"refType\":null,\"conclusion\":null,\"stage\":null,\"operating\":\"业务科室\",\"remarks\":\"待处理。\",\"jbr\":null,\"flagRegister\":null,\"deleteFlag\":\"0\",\"createTime\":null,\"updateTime\":null,\"files\":null}]}}"
        val gson = com.google.gson.Gson()
        val entity = gson.fromJson(jsonStr,AccountInfoEntity::class.java)
        println("MMKV->entity.access_token=${entity.access_token}")
        val isEncodeSuccess = App.kv.encode("ABC",jsonStr)
        println("MMKV->isEncodeSuccess=$isEncodeSuccess")
        val decodeByMMKV = App.kv.decodeParcelable("ABC",AccountInfoEntity::class.java)
        println("MMKV->decodeByMMKV?.access_token=${decodeByMMKV?.access_token}")
    }
```

**Comment by parcool** [comment]
Now I know the mistake what I make, mmkv.encode("Key",String) and mmkv. decodeParcelable("Key",Class<T>)

**Comment by ChawLoo** [comment]
I got this issue too, why it happened in 2021 and 2023? it over two years, did you resolved？
