### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found

### ISSUE THREAD

**Issue by kongxinxin** [Tencent/MMKV#740]
我在common moudel里面引用MMKV  api 'com.tencent:mmkv-static:1.2.10' ，然后在app moudel中的Application进行初始化
  MMKV.initialize(this);每次打开App都闪退,必现.

2021-08-17 16:54:57.217 14023-14023/com.neway.truck E/CrashReport: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.tencent.mmkv.MMKV.e(:193)
        at com.tencent.mmkv.MMKV.i(:180)
        at com.tencent.mmkv.MMKV.h(:84)
        at com.neway.truck.app.NiWangApplication.onCreate(:28)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7178)
        at android.app.ActivityThread.access$1500(ActivityThread.java:269)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2159)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by lingol** [comment]
Check your project setting. This error has nothing to do with MMKV or any NDK lib in general. 
So please don't complain about it here.
