### ISSUE TITLE
UnsatisfiedLinkError:/lib/arm64/libmmkv.so" has bad ELF magic: 00000000

### ISSUE THREAD

**Issue by yezizaiqiutian** [Tencent/MMKV#789]
### The language of MMKV

>android java

### The platform of MMKV

> Android

### The installation of MMKV

> gradle

### What's the issue?
线上偶现初始化报错,很少出现,只有两个华为型号的手机会有这个问题,刚开始怀疑是armeabi兼容性问题,但是报的错误是arm64的问题,麻烦帮忙看下为什么会出现这样的崩溃

```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/[项目名称]-8Mekl2afIfGWOlUjECg9qw==/lib/arm64/libmmkv.so" has bad ELF magic: 00000000
 at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
 at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
 at java.lang.System.loadLibrary(System.java:1668)
 at com.tencent.mmkv.MMKV.initialize(MMKV.java:99)
 at com.tencent.mmkv.MMKV.initialize(MMKV.java:70)
 ...
 at com.stub.StubApp.onCreate(SourceFile:119)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
 at android.app.ActivityThread.access$2200(ActivityThread.java:296)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:213)
 at android.app.ActivityThread.main(ActivityThread.java:8178)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Back traces ends.
```

辛苦大佬

**Comment by lingol** [comment]
I have no idea. Why don't you Google it? #308

**Comment by yijiangqiu1** [comment]
@yezizaiqiutian 请问这个问题有解决方案吗

**Comment by caoyali** [comment]
你是怎么解决的呀，我也是华为也是arm64 出现了问题
