### ISSUE TITLE
couldn't find "libmmkv.so"

### ISSUE THREAD

**Issue by nysin** [Tencent/MMKV#793]
## Note:
E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxx-P0jPOBsbrSPPWc7ClAHOQA==/base.apk"],nativeLibraryDirectories=[/data/app/xxx-P0jPOBsbrSPPWc7ClAHOQA==/lib/arm, /data/app/xxx-P0jPOBsbrSPPWc7ClAHOQA==/base.apk!/lib/armeabi, /system/lib, /system/vendor/lib]]] couldn't find "libmmkv.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:84)
        at xxx.BrainApp.onCreate(BrainApp.kt:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

### The language of MMKV

>  Kotlin 1.3.72

### The version of MMKV
 v1.2.11 

but i use version 1.0.5 is no problem

### The platform of MMKV

 Android

### The installation of MMKV
 Maven

### What's the issue?

 app crash

### What's the log of MMKV when that happened?

-----------------
compileSdk 31.  
MMKV.initialize(this) in the oncreate() in the application class

**Comment by lingol** [comment]
Did you use the armeabi arch? MMKV doesn't support armeabi anymore.

**Comment by nysin** [comment]
> Did you use the armeabi arch? MMKV doesn't support armeabi anymore.

Yeah,you are right.i remove 'armeabi' config,it run no problem .thx
