### ISSUE TITLE
realme Q arm64 couldn't find "libmmkv.so"

### ISSUE THREAD

**Issue by Vicent9920** [Tencent/MMKV#801]
## Note:
MMKV初始化崩溃

### The language of MMKV

> Java

### The version of MMKV

>  v1.2.11

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

> Post the outputs or screenshots for errors.
 ```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.vi.vcredit-Yk_t_ZPek3Mxz7ZaMnweSw==/base.apk"],nativeLibraryDirectories=[/data/app/com.vi.vcredit-Yk_t_ZPek3Mxz7ZaMnweSw==/lib/arm64, /system/lib64]]] couldn't find "libmmkv.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:84)
        at com.vi.vcredit.base.ApplicationController.initMMKV(ApplicationController.java:123)
        at com.vi.vcredit.base.ApplicationController.onCreate(ApplicationController.java:66)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6309)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7217)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
 
 ```

### What's the log of MMKV when that happened?
> 初始化崩溃，日志显示为找不到so地址。关键点在于`apk`安装使用正常，使用`aab`安装则崩溃。
so架构尝试使用了下面五种，依然不行。
``` abiFilters "armeabi", "armeabi-v7a", "arm64-v8a", "x86","x86_64"```
下载`demo`运行一样不行。
其它设备正常，唯独下列设备不行！
![微信图片_20211221112112](https://user-images.githubusercontent.com/17283445/146865575-a8f1d65c-a490-4076-b78c-eb98ca9757d9.png)

**Comment by lingol** [comment]
As far as I can see, it's **nothing to do with MMKV**. 
You should check your _aab_ package to see if it really contains the file libmmkv.so. 
And if it does, then check the compatibility of _aab_ on this specific phone.

**Comment by Reallym404** [comment]
你的问题解决了吗，遇到和你一样的问题。真我手机崩溃，其他手机正常

**Comment by MrDragonForest** [comment]
> 

是不是安装aab的时候,我也遇到了
