### ISSUE TITLE
启动崩溃 Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: d4.b.values []

### ISSUE THREAD

**Issue by SmallerRui** [Tencent/MMKV#831]
gradle版本: classpath 'com.android.tools.build:gradle:7.1.1'

kotlin版本: classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"

Android studio版本:Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 2, 2022

`2022-02-11 17:26:59.102 12284-12284/com.td.ispirit E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.td.ispirit, PID: 12284
    java.lang.ExceptionInInitializerError
        at com.tencent.mmkv.MMKV.l(MMKV.java:82)
        at com.td.ispirit.MainApplication.onCreate(MainApplication.kt:17)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7588)
        at android.app.ActivityThread.access$2600(ActivityThread.java:260)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: d4.b.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
        at java.util.EnumMap.<init>(EnumMap.java:138)
        at com.tencent.mmkv.MMKV.<clinit>(MMKV.java:53)
        at com.tencent.mmkv.MMKV.l(MMKV.java:82) 
        at com.td.ispirit.MainApplication.onCreate(MainApplication.kt:17) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7588) 
        at android.app.ActivityThread.access$2600(ActivityThread.java:260) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
     Caused by: java.lang.NoSuchMethodException: d4.b.values []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at java.lang.Enum.enumValues(Enum.java:267)
        at java.lang.Enum.access$000(Enum.java:61) 
        at java.lang.Enum$1.create(Enum.java:277) 
        at java.lang.Enum$1.create(Enum.java:275) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2428) 
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755) 
        at java.util.EnumMap.<init>(EnumMap.java:138) 
        at com.tencent.mmkv.MMKV.<clinit>(MMKV.java:53) 
        at com.tencent.mmkv.MMKV.l(MMKV.java:82) 
        at com.td.ispirit.MainApplication.onCreate(MainApplication.kt:17) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7588) 
        at android.app.ActivityThread.access$2600(ActivityThread.java:260) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) `

**Comment by lingol** [comment]
There's absolutely **nothing useful** in your post. Please follow the issue template, provide as much info as possible.

**Comment by SmallerRui** [comment]
已解决,忘记添加混淆规则!
`-keep class com.tencent.mmkv.* {*;}`
