### ISSUE TITLE
版本：com.tencent:mmkv-static:1.2.13

### ISSUE THREAD

**Issue by flashable** [Tencent/MMKV#873]
2022-04-13 18:23:34.142 2793-3292/? E/OllieTelephony: sendFullData err:1
2022-04-13 18:23:34.834 2793-3292/? E/SpeedLimitTestNotifier: mIsTopActivity false
2022-04-13 18:23:35.815 7947-7947/? E/libc: Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
2022-04-13 18:23:35.815 7947-7947/? E/com.zksg.smart: LoadAppImageStartupCache enabled : 1
2022-04-13 18:23:35.818 7947-7947/? E/com.zksg.smart: Not starting debugger since process cannot load the jdwp agent.
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is JAD
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is NOP
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is NOH
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is OCE
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is BRQ
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is ANG
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is ELS
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is ANA
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is TAH
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is LIO
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_AbmConfigParser: getAbmSwitchStatus, appPackageName in map is TAS
2022-04-13 18:23:35.898 2793-3631/? E/Hicom_XEngineProc: isSupportNearMp. switch disabled
2022-04-13 18:23:35.901 7947-8021/? E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@136d59e
2022-04-13 18:23:35.943 7947-7947/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zksg.smart, PID: 7947
    java.lang.ExceptionInInitializerError
        at com.tencent.mmkv.MMKV.a(Unknown Source:0)
        at com.zksg.smart.app.AppApplication.a(:1)
        at com.zksg.smart.app.j.c(Unknown Source:12)
        at g.a.b.b.c.b(Unknown Source:10)
        at com.zksg.smart.b.d.a(:6)
        at com.zksg.smart.app.AppApplication.onCreate(Unknown Source:55)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7588)
        at android.app.ActivityThread.access$2600(ActivityThread.java:260)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.tencent.mmkv.b.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
        at java.util.EnumMap.<init>(EnumMap.java:138)
        at com.tencent.mmkv.MMKV.<clinit>(Unknown Source:4)
        at com.tencent.mmkv.MMKV.a(Unknown Source:0) 
        at com.zksg.smart.app.AppApplication.a(:1) 
        at com.zksg.smart.app.j.c(Unknown Source:12) 
        at g.a.b.b.c.b(Unknown Source:10) 
        at com.zksg.smart.b.d.a(:6) 
        at com.zksg.smart.app.AppApplication.onCreate(Unknown Source:55) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7588) 
        at android.app.ActivityThread.access$2600(ActivityThread.java:260) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
     Caused by: java.lang.NoSuchMethodException: com.tencent.mmkv.b.values []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at java.lang.Enum.enumValues(Enum.java:267)
        at java.lang.Enum.access$000(Enum.java:61) 
        at java.lang.Enum$1.create(Enum.java:277) 
        at java.lang.Enum$1.create(Enum.java:275) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2428) 
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755) 
        at java.util.EnumMap.<init>(EnumMap.java:138) 
        at com.tencent.mmkv.MMKV.<clinit>(Unknown Source:4) 
        at com.tencent.mmkv.MMKV.a(Unknown Source:0) 
        at com.zksg.smart.app.AppApplication.a(:1) 
        at com.zksg.smart.app.j.c(Unknown Source:12) 
        at g.a.b.b.c.b(Unknown Source:10) 
        at com.zksg.smart.b.d.a(:6) 
        at com.zksg.smart.app.AppApplication.onCreate(Unknown Source:55) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7588) 
        at android.app.ActivityThread.access$2600(ActivityThread.java:260) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
2022-04-13 18:23:35.946 2878-2942/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: No phone privilege permission
        at com.android.providers.telephony.TpProviderHw.checkPhonePrivilegePermission(TpProviderHw.java:2491)
        at com.android.providers.telephony.TpProviderHw.query(TpProviderHw.java:1192)
        at com.android.providers.telephony.TpProviderHw.query(TpProviderHw.java:887)
        at com.android.providers.telephony.TpProviderHw.query(TpProviderHw.java:880)
        at com.android.providers.telephony.TelephonyProvider.query(TelephonyProvider.java:1036)
        at android.content.ContentProvider.query(ContentProvider.java:1218)
        at android.content.ContentProvider.query(ContentProvider.java:1311)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:271)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
        at android.os.Binder.execTransactInternal(Binder.java:1028)
        at android.os.Binder.execTransact(Binder.java:1001)

**Comment by lingol** [comment]
Sorry but what is your problem?

**Comment by flashable** [comment]
> 



> Sorry but what is your problem?

java.lang.ExceptionInInitializerError
at com.tencent.mmkv.MMKV.a(Unknown Source:0)
at com.zksg.smart.app.AppApplication.a(:1)
at com.zksg.smart.app.j.c(Unknown Source:12)

**Comment by flashable** [comment]
> Sorry but what is your problem?
debug is not problem,but build release to MMKV  ExceptionInInitializerError

at com.tencent.mmkv.MMKV.a(Unknown Source:0)
        at com.zksg.smart.app.AppApplication.a(:1)
        at com.zksg.smart.app.j.c(Unknown Source:12)
        at j.a.b.b.c.b(Unknown Source:10)
        at com.zksg.smart.b.d.a(:6)
        at com.zksg.smart.app.AppApplication.onCreate(Unknown Source:55)

**Comment by lingol** [comment]
Your call stacks are pro-guarded. You should provide un proguard call stacks. Otherwise I don't know what is it really doing.

**Comment by lingol** [comment]
If it only happens in release build, it's highly likely that you missed the proguard file from MMKV leading to stripping some MMKV methods.

**Comment by lingol** [comment]
Hello, any update?

**Comment by lingol** [comment]
Closed due to inactive.
