### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by billdizl** [Tencent/MMKV#880]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.
main (native): tid=1 systid=1768 
#00 pc 0x4db10 libc.so 
#01 pc 0x389f2c libart.so 
#02 pc 0x3b42d0 libart.so 
#03 pc 0x2d4054 libart.so 
#04 pc 0x209188 libart.so 
#05 pc 0x175b4a4 base.vdex 
#06 pc 0x2ca9e8 libart.so 
#07 pc 0x2ee6b8 libart.so 
#08 pc 0x2ed4fc libart.so 
#09 pc 0x76d46c libart.so 
#10 pc 0x2c5014 libart.so 
#11 pc 0xc3e1e8 base.vdex 
#12 pc 0x27d840 libart.so 
#13 pc 0x27c9e8 libart.so 
#14 pc 0x2d4178 libart.so 
#15 pc 0x2ca9e8 libart.so 
#16 pc 0x28ad7c libart.so 
#17 pc 0x364b88 libart.so 
#18 pc 0x43c648 libart.so 
#19 pc 0x2c4894 libart.so 
#20 pc 0xc1213a base.vdex 
#21 pc 0x27d840 libart.so 
#22 pc 0x2ede78 libart.so 
#23 pc 0x40a06c libart.so 
#24 pc 0x2c4f94 libart.so 
#25 pc 0xbed5a0 base.vdex 
#26 pc 0x27d840 libart.so 
#27 pc 0x27c9e8 libart.so 
#28 pc 0x2d4178 libart.so 
       at com.tencent.mmkv.MMKV.getDefaultMMKV(Native method)
       at com.tencent.mmkv.MMKV.defaultMMKV(MMKV.java:471)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1261)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7226)
       at android.app.ActivityThread.access$1800(ActivityThread.java:284)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

### The language of MMKV

> e.g. Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
phone: vivo  V2028    Android 12

### The platform of MMKV

> e.g.  Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
As the issue template has said. all issues without symbolized native call stacks will be ignored.

**Comment by billdizl** [comment]
main (native): tid=1 systid=24979 
#00 pc 0x608e8 libc.so 
#01 pc 0x1c427 split_config.armeabi_v7a.apk!libmmkv.so 
#02 pc 0x19283 split_config.armeabi_v7a.apk!libmmkv.so 
#03 pc 0x18ff1 split_config.armeabi_v7a.apk!libmmkv.so 
#04 pc 0x18cc9 split_config.armeabi_v7a.apk!libmmkv.so 
#05 pc 0x129b9 split_config.armeabi_v7a.apk!libmmkv.so 
#06 pc 0xfb9d split_config.armeabi_v7a.apk!libmmkv.so 
       at com.tencent.mmkv.MMKV.encodeString(Native method)
       at com.tencent.mmkv.MMKV.encode(MMKV.java:660)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7886)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:970)




Signal Catcher (runnable): tid=6 systid=24991 
#00 pc 0x3729d5 libart.so 
#01 pc 0x4415b7 libart.so 
#02 pc 0x43cf83 libart.so 
#03 pc 0x459b59 libart.so 
#04 pc 0x455133 libart.so 
#05 pc 0x45466b libart.so 
#06 pc 0x453d65 libart.so 
#07 pc 0x40c787 libart.so 
#08 pc 0x41c363 libart.so 
#09 pc 0x41b6af libart.so 
#10 pc 0xaacd3 libc.so 
#11 pc 0x640a3 libc.so 


HeapTaskDaemon (waiting): tid=7 systid=24993 
#00 pc 0x5e368 libc.so 
#01 pc 0x130fb3 libart.so 
#02 pc 0x219275 libart.so 
#03 pc 0x219965 libart.so 
       at dalvik.system.VMRuntime.runHeapTasks(Native method)
       at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:531)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:923)


Jit thread pool worker thread 0 (native): tid=8 systid=24992 
#00 pc 0x5e368 libc.so 
#01 pc 0x130fb3 libart.so 
#02 pc 0x45b063 libart.so 
#03 pc 0x45a775 libart.so 
#04 pc 0x45a3c9 libart.so 
#05 pc 0xaacd3 libc.so 
#06 pc 0x640a3 libc.so 


FinalizerDaemon (waiting): tid=10 systid=24995 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:923)


FinalizerWatchdogDaemon (waiting): tid=11 systid=24996 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:341)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:321)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:923)


Binder:24979_1 (native): tid=12 systid=24997 
#00 pc 0x9ae40 libc.so 
#01 pc 0x6936f libc.so 
#02 pc 0x39eb7 libbinder.so 
#03 pc 0x3a011 libbinder.so 
#04 pc 0x3a6e7 libbinder.so 
#05 pc 0x53bf5 libbinder.so 
#06 pc 0xee95 libutils.so 
#07 pc 0x6da83 libandroid_runtime.so 
#08 pc 0xe9dd libutils.so 
#09 pc 0xaacd3 libc.so 
#10 pc 0x640a3 libc.so 

Binder:24979_2 (native): tid=13 systid=24998 
#00 pc 0x9ae40 libc.so 
#01 pc 0x6936f libc.so 
#02 pc 0x39eb7 libbinder.so 
#03 pc 0x3a011 libbinder.so 
#04 pc 0x3a6e7 libbinder.so 
#05 pc 0x53bf5 libbinder.so 
#06 pc 0xee95 libutils.so 
#07 pc 0x6da83 libandroid_runtime.so 
#08 pc 0xe9dd libutils.so 
#09 pc 0xaacd3 libc.so 
#10 pc 0x640a3 libc.so

**Comment by lingol** [comment]
As the issue template has said. all issues without symbolized native call stacks will be ignored.

**Comment by lingol** [comment]
Your native call stacks is **STILL** not symbolized.
