### ISSUE TITLE
打包初始化异常

### ISSUE THREAD

**Issue by panyingdaoz** [Tencent/MMKV#888]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

如下是异常信息
2022-05-16 09:41:37.595 8397-8397/? E/nspection:cras: Unknown bits set in runtime_flags: 0x8000
2022-05-16 09:41:38.842 8397-8397/com.enode.inspection E/CrashReport: --------------------------------------------------------------------------------------------
2022-05-16 09:41:38.842 8397-8397/com.enode.inspection E/CrashReport: --------------------------------------------------------------------------------------------
2022-05-16 09:41:38.974 8397-8397/com.enode.inspection E/CrashReport-Native: current stack have not bugly line,return default prefix
2022-05-16 09:41:38.976 8397-8397/com.enode.inspection E/CrashReport-Native: find cls error com/tencent/bugly/crashreport/crash/jni/NativeCrashHandler 
2022-05-16 09:41:38.976 8397-8397/com.enode.inspection E/CrashReport-Native: back up bugly classes error
2022-05-16 09:41:39.018 8397-8397/com.enode.inspection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.enode.inspection:crash, PID: 8397
    java.lang.ExceptionInInitializerError
        at com.tencent.mmkv.MMKV.i(:82)
        at r1.k.h(:130)
        at com.enode.inspection.app.AppApplication.onCreate(:49)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6516)
        at android.app.ActivityThread.access$1500(ActivityThread.java:226)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1912)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: V3.c.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
        at java.util.EnumMap.<init>(EnumMap.java:138)
        at com.tencent.mmkv.MMKV.<clinit>(:53)
        at com.tencent.mmkv.MMKV.i(:82) 
        at r1.k.h(:130) 
        at com.enode.inspection.app.AppApplication.onCreate(:49) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6516) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1912) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
     Caused by: java.lang.NoSuchMethodException: V3.c.values []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at java.lang.Enum.enumValues(Enum.java:267)
        at java.lang.Enum.access$000(Enum.java:61) 
        at java.lang.Enum$1.create(Enum.java:277) 
        at java.lang.Enum$1.create(Enum.java:275) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2428) 
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755) 
        at java.util.EnumMap.<init>(EnumMap.java:138) 
        at com.tencent.mmkv.MMKV.<clinit>(:53) 
        at com.tencent.mmkv.MMKV.i(:82) 
        at r1.k.h(:130) 
        at com.enode.inspection.app.AppApplication.onCreate(:49) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6516) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1912) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
2022-05-16 09:41:39.019 8397-8397/com.enode.inspection E/CrashReport: Java Crash Happen cause by main(2)
2022-05-16 09:41:39.038 8397-8397/com.enode.inspection E/memtrack: Couldn't load memtrack module
2022-05-16 09:41:40.239 8397-8397/com.enode.inspection E/CrashReport: stack frame :13, has cause true
2022-05-16 09:41:40.249 8397-8397/com.enode.inspection E/CrashReport: #++++++++++Record By Bugly++++++++++#
2022-05-16 09:41:40.249 8397-8397/com.enode.inspection E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
2022-05-16 09:41:40.250 8397-8397/com.enode.inspection E/CrashReport: # PKG NAME: com.enode.inspection
2022-05-16 09:41:40.250 8397-8397/com.enode.inspection E/CrashReport: # APP VER: 1.0.1
2022-05-16 09:41:40.250 8397-8397/com.enode.inspection E/CrashReport: # SDK VER: 4.0.4
2022-05-16 09:41:40.252 8397-8397/com.enode.inspection E/CrashReport: # LAUNCH TIME: 2022-05-16 09:41:38
2022-05-16 09:41:40.252 8397-8397/com.enode.inspection E/CrashReport: # CRASH TYPE: JAVA_CRASH
2022-05-16 09:41:40.253 8397-8397/com.enode.inspection E/CrashReport: # CRASH TIME: 2022-05-16 09:41:40
2022-05-16 09:41:40.253 8397-8397/com.enode.inspection E/CrashReport: # CRASH PROCESS: com.enode.inspection:crash
2022-05-16 09:41:40.253 8397-8397/com.enode.inspection E/CrashReport: # CRASH FOREGROUND: false
2022-05-16 09:41:40.253 8397-8397/com.enode.inspection E/CrashReport: # CRASH THREAD: main
2022-05-16 09:41:40.253 8397-8397/com.enode.inspection E/CrashReport: # REPORT ID: 6ca5a582-2725-4210-825c-c2b4d4da4d3a
2022-05-16 09:41:40.254 8397-8397/com.enode.inspection E/CrashReport: # CRASH DEVICE: fail UNROOT
2022-05-16 09:41:40.254 8397-8397/com.enode.inspection E/CrashReport: # RUNTIME AVAIL RAM:4429721600 ROM:55237230592 SD:55237242880
2022-05-16 09:41:40.257 8397-8397/com.enode.inspection E/CrashReport: # RUNTIME TOTAL RAM:3992580096 ROM:55957676032 SD:55957676032
2022-05-16 09:41:40.257 8397-8397/com.enode.inspection E/CrashReport: # CRASH STACK: 
2022-05-16 09:41:40.257 8397-8397/com.enode.inspection E/CrashReport: java.lang.ExceptionInInitializerError
        at com.tencent.mmkv.MMKV.i(:82)
        at r1.k.h(:130)
        at com.enode.inspection.app.AppApplication.onCreate(:49)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6516)
        at android.app.ActivityThread.access$1500(ActivityThread.java:226)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1912)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: V3.c.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
        at java.util.EnumMap.<init>(EnumMap.java:138)
        at com.tencent.mmkv.MMKV.<clinit>(:53)
        at com.tencent.mmkv.MMKV.i(:82) 
        at r1.k.h(:130) 
        at com.enode.inspection.app.AppApplication.onCreate(:49) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6516) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1912) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
     Caused by: java.lang.NoSuchMethodException: V3.c.values []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at java.lang.Enum.enumValues(Enum.java:267)
        at java.lang.Enum.access$000(Enum.java:61) 
        at java.lang.Enum$1.create(Enum.java:277) 
        at java.lang.Enum$1.create(Enum.java:275) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2428) 
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755) 
        at java.util.EnumMap.<init>(EnumMap.java:138) 
        at com.tencent.mmkv.MMKV.<clinit>(:53) 
        at com.tencent.mmkv.MMKV.i(:82) 
        at r1.k.h(:130) 
        at com.enode.inspection.app.AppApplication.onCreate(:49) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6516) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1912) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
2022-05-16 09:41:40.257 8397-8397/com.enode.inspection E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
2022-05-16 09:41:40.633 8397-8397/com.enode.inspection E/CrashReport: sys default last handle start!

**Comment by lingol** [comment]
There's absolutely nothing valuable in your logs. Please provide un-pro-guarded MMKV call stacks, and symbolized **native** call stacks.

**Comment by lingol** [comment]
And logs from logcat as well.

**Comment by panyingdaoz** [comment]
没有做混淆运行时没有问题的，但是混淆后运行初始化就崩溃了。

**Comment by lingol** [comment]
Then you must have miss-handled the proguard setting from MMKV. #31

**Comment by panyingdaoz** [comment]
proguard应当怎么配置呢？

**Comment by lingol** [comment]
Google about it. It's the same as any 3rd library.
