### ISSUE TITLE
升级后第一次打开应用有几率会在Service中报NullPointerException异常

### ISSUE THREAD

**Issue by 1149452014** [Tencent/MMKV#902]
2022-06-09 10:08:33
App Version: 3.1.7_217
OS Version: 7.1.2_25
Vendor: rockchip
Model: rk32_88XT
CPU ABI: [Ljava.lang.String;@4e75386

java.lang.RuntimeException: Unable to create service com.cloudshare.faceaccess.service.MainService: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tencent.mmkv.MMKV.getInt(java.lang.String, int)' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3207)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6141)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tencent.mmkv.MMKV.getInt(java.lang.String, int)' on a null object reference
	at com.cloudshare.faceaccess.util.SharedPreferencesUtil.getHealthServiceType(SharedPreferencesUtil.java:586)
	at com.cloudshare.faceaccess.service.MainService.initZhongYunHc(MainService.java:301)
	at com.cloudshare.faceaccess.service.MainService.init(MainService.java:187)
	at com.cloudshare.faceaccess.service.MainService.onCreate(MainService.java:111)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3197)
	... 8 more

**Comment by lingol** [comment]
As far as I can tell, it's none of MMKV's problem. Either you are calling `MMKV.getInt()` on a null MMKV, or you pass a null key to that call.
