### ISSUE TITLE
StrictMode 问题

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [Tencent/MMKV#904]
mmkv-static.1.2.10

 MMKV.initialize(this)  初始化耗时

2022-06-11 10:43:30.903 27100-27100/com.wsecar.wsjcsj D/StrictMode: StrictMode policy violation; ~duration=516 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:131)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8514)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:813)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:779)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:770)
        at android.app.ContextImpl.getFilesDir(ContextImpl.java:815)
        at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:270)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:82)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
        at android.app.ActivityThread.access$1700(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2022-06-11 10:43:30.903 27100-27100/com.wsecar.wsjcsj D/AndroidRuntime: Shutting down VM

**Comment by lingol** [comment]
It's none of MMKV's problem. "getFilesDir()" is just a simple system SDK call. There's nothing we can do about it.
I don't know why you complain about it here.
