### ISSUE TITLE
MMKV初始化，调用loadLibrary("mmkv")报错，找不到到Lcom/wangsu/muf/plugin/PluginHelper类

### ISSUE THREAD

**Issue by ledding** [Tencent/MMKV#906]
### The language of MMKV
> Java

### The version of MMKV
> v1.2.13  

### The platform of MMKV
> Android

### The installation of MMKV
> Maven

### What's the issue?
以下错误发生的代码
```
        MMKV.initialize(context, new MMKV.LibLoader() {
            @Override
            public void loadLibrary(String libName) {
                Logger.t("ReLinker").d("libName = "+libName);
                ReLinker.loadLibrary(context,libName);
            }
        });
        kv = MMKV.defaultMMKV();
```

以下是错误日志
 
```
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/wangsu/muf/plugin/PluginHelper;
        at com.getkeepsafe.relinker.SystemLibraryLoader.loadLibrary(SystemLibraryLoader.java:25)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:163)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at cn.microants.merchants.lib.base.utils.SharedPreferencesManager$1.loadLibrary(SharedPreferencesManager.java:19)
        at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:189)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:109)
        at cn.microants.merchants.lib.base.utils.SharedPreferencesManager.init(SharedPreferencesManager.java:15)
        at cn.microants.merchants.AppContext.initMmvk(AppContext.java:356)
        at cn.microants.merchants.AppContext.onCreate(AppContext.java:272)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1205)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7683)
        at android.app.ActivityThread.access$2400(ActivityThread.java:270)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2358)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:8731)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1085)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.wangsu.muf.plugin.PluginHelper" on path: DexPathList[[zip file "/data/app/~~U0hmWxNNqmdtRlqfFz-5FA==/cn.microants.merchants-16otcvtOjTc0JlIaIjgF5w==/base.apk"],nativeLibraryDirectories=[/data/app/~~U0hmWxNNqmdtRlqfFz-5FA==/cn.microants.merchants-16otcvtOjTc0JlIaIjgF5w==/lib/arm64, /data/app/~~U0hmWxNNqmdtRlqfFz-5FA==/cn.microants.merchants-16otcvtOjTc0JlIaIjgF5w==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system_ext/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.getkeepsafe.relinker.SystemLibraryLoader.loadLibrary(SystemLibraryLoader.java:25) 
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:163) 
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136) 
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70) 
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51) 
        at cn.microants.merchants.lib.base.utils.SharedPreferencesManager$1.loadLibrary(SharedPreferencesManager.java:19) 
        at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:189) 
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:181) 
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:109) 
        at cn.microants.merchants.lib.base.utils.SharedPreferencesManager.init(SharedPreferencesManager.java:15) 
        at cn.microants.merchants.AppContext.initMmvk(AppContext.java:356) 
        at cn.microants.merchants.AppContext.onCreate(AppContext.java:272) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1205) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7683) 
        at android.app.ActivityThread.access$2400(ActivityThread.java:270) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2358) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:228) 
        at android.app.ActivityThread.main(ActivityThread.java:8731) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1085) 
```

**Comment by lingol** [comment]
We don't accept issues on load library failure anymore. It's always almost a project-setting problem.
A qualified developer should solve such a problem by themself.

**Comment by tomgreco** [comment]
Same issue, @lingol you suck
