### ISSUE TITLE
Android: no mmkv in java.library.path

### ISSUE THREAD

**Issue by Jerry805** [Tencent/MMKV#909]
### The language of MMKV
Kotlin

### The version of MMKV
1.2.13

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?

no mmkv in java.library.path when init mmkv in unit test.

### What's the log of MMKV when that happened?

no mmkv in java.library.path: [C:\Program Files\Android\Android Studio\jre\bin, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\Java\jdk1.8.0_301\bin, C:\Program Files\Git\cmd, C:\Program Files\dotnet\, C:\Users\UI-21-5-11-2\AppData\Local\Microsoft\WindowsApps, C:\Users\UI-21-5-11-2\AppData\Local\Android\Sdk\platform-tools, C:\Program Files\Bandizip\, D:\Program Files\scrcpy, D:\Program Files\apache-maven-3.8.5\bin, ., .]
java.lang.UnsatisfiedLinkError: no mmkv in java.library.path: [C:\Program Files\Android\Android Studio\jre\bin, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\Java\jdk1.8.0_301\bin, C:\Program Files\Git\cmd, C:\Program Files\dotnet\, C:\Users\UI-21-5-11-2\AppData\Local\Microsoft\WindowsApps, C:\Users\UI-21-5-11-2\AppData\Local\Android\Sdk\platform-tools, C:\Program Files\Bandizip\, D:\Program Files\scrcpy, D:\Program Files\apache-maven-3.8.5\bin, ., .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:84)
	at com.example.gradledemo.MainApplication.onCreate(MainApplication.kt:13)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$2(AndroidTestEnvironment.java:350)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:350)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by lingol** [comment]
Duplicated with #906

**Comment by loflv** [comment]
请问有解决吗？我使用Robolectric进行单元测试时也遇到了相同的问题，看问题似乎是mmkv企图在本地寻找,这当然是找不到的，那应该怎么办呢？

**Comment by tomgreco** [comment]
Same issue, no solution.
@lingol be a better human please.
