### ISSUE TITLE
Application的attachBaseContext里面初始化(或者Application的onCreate里面初始化)MMKV后马上调用getBoolean的话，会抛异常

### ISSUE THREAD

**Issue by alen252** [Tencent/MMKV#942]
Note:
An crash issue will be ignored & closed in a week without logs.

The language of MMKV
Java

The version of MMKV
v1.0.15
Note: For versions older than the latest version, please upgrade before posting any issue.
We don't have much time for old version tech support.

The platform of MMKV
Android

The installation of MMKV
Maven

What's the issue?
Application的attachBaseContext里面初始化(或者Application的onCreate里面初始化)MMKV后马上调用getBoolean的话，会抛异常

Process: com.hikretail.app, PID: 20132
    java.lang.ExceptionInInitializerError
        at com.xxxx.dblib.sp.SpFactory.getMMKV(SpFactory.java:22)
        at com.xxxx.dblib.sp.SpUtil.getSP(SpUtil.java:21)
        at com.xxxx.dblib.sp.SpUtil.getBoolean(SpUtil.java:62)
        at com.xxxx.xxxxx.initPrivacyTransformComplete(AAA.java:362)
        at com.xxxx.xxxx.onCreate(AAA.java:98)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7202)
        at android.app.ActivityThread.access$2200(ActivityThread.java:296)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

代码：
MMKV.initialize(this);
SpUtil.getBoolean(IConstant.SP_HAS_AGREE_USERPRIVACY, false)

**Comment by lingol** [comment]
Please provide the logs of MMKV from logcat.

**Comment by lingol** [comment]
By the way, your version v1.0.15 is **way older** than the latest version. Please **upgrade** to the latest version first.

**Comment by alen252** [comment]
> Please provide the logs of MMKV from logcat.

2022-08-26 17:24:09.146 21076-21076/com.xxxx.app I/MMKV: page size:4096
2022-08-26 17:24:09.146 21076-21076/com.xxxx.app I/MMKV: root dir: /data/user/0/com.hikretail.app/files/mmkv

**Comment by alen252** [comment]
> By the way, your version v1.0.15 is **way older** than the latest version. Please **upgrade** to the latest version first.

I will upgrade. Then try again.

**Comment by alen252** [comment]
初始化MMKV是调用的MMKV.mmkvWithID(mmkvId, MMKV.MULTI_PROCESS_MODE)

**Comment by lingol** [comment]
Another look into your crash stack, the exception is thrown from some wrapper class, not from MMKV. As far as I can see, you should check the code inside that class instead of complaining to me.
>java.lang.ExceptionInInitializerError
at com.xxxx.dblib.sp.SpFactory.getMMKV(SpFactory.java:22)

**Comment by alen252** [comment]
> 
SpFactory.getMMKV：
MMKV.mmkvWithID(mmkvId, MMKV.MULTI_PROCESS_MODE)
I upgrade to 1.2.14. The problem still happen.

**Comment by lingol** [comment]
> Another look into your crash stack, the exception is thrown from some wrapper class, not from MMKV. As far as I can see, you should check the code inside that class instead of complaining to me.
> 
> > java.lang.ExceptionInInitializerError
> > at com.xxxx.dblib.sp.SpFactory.getMMKV(SpFactory.java:22)

I won't repeat myself.

**Comment by alen252** [comment]
> > Another look into your crash stack, the exception is thrown from some wrapper class, not from MMKV. As far as I can see, you should check the code inside that class instead of complaining to me.
> > > java.lang.ExceptionInInitializerError
> > > at com.xxxx.dblib.sp.SpFactory.getMMKV(SpFactory.java:22)
> 
> I won't repeat myself.
SpFactory.getMMKV  the code inside:
MMKV.mmkvWithID(mmkvId, MMKV.MULTI_PROCESS_MODE)

**Comment by lingol** [comment]
> > Another look into your crash stack, the exception is thrown from some wrapper class, not from MMKV. As far as I can see, you should check the code inside that class instead of complaining to me.
> > > java.lang.ExceptionInInitializerError
> > > at com.xxxx.dblib.sp.SpFactory.getMMKV(SpFactory.java:22)
> 
> I won't repeat myself.

I won't repeat myself.

**Comment by lingol** [comment]
Google about `java.lang.ExceptionInInitializerError` and solve it yourself.

**Comment by lingol** [comment]
https://rollbar.com/blog/java-exceptionininitializererror-runtime-error/
