### ISSUE TITLE
MMKV.initialize occur native crash

### ISSUE THREAD

**Issue by superoidlau** [Tencent/MMKV#950]
## Note:
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/app_package_name-PIJ2yDZKQu-vJOr5zbqP3A==/lib/arm64/libmmkv.so" has bad ELF magic: 00000000
	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1668)
	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:121)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:108)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:71)

### The language of MMKV

> java

### The version of MMKV

> [v1.2.8](com.tencent:mmkv-static:1.2.8)

### The platform of MMKV

> Android

### The installation of MMKV

> Gradle

### What's the issue?

> java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/app_package_name-PIJ2yDZKQu-vJOr5zbqP3A==/lib/arm64/libmmkv.so" has bad ELF magic: 00000000
	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1668)
	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:121)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:108)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:71)

Can you provide some idea for this issue?
thanks.

**Comment by superoidlau** [comment]
implementation 'com.tencent:mmkv-static:1.2.8'

**Comment by lingol** [comment]
We don't accept issues on `java.lang.UnsatisfiedLinkError` . It's clear that it has nothing to do with the library developer.
You should check your package and project setting.

**Comment by superoidlau** [comment]
> We don't accept issues on `java.lang.UnsatisfiedLinkError` . It's clear that it has nothing to do with the library developer. You should check your package and project setting.

ok, thanks.
