### ISSUE TITLE
dlopen failed: library "libmmkv.so" not found

### ISSUE THREAD

**Issue by lulalalei** [Tencent/MMKV#958]
Non-fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:110)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:90)

HAPPENED IN **com.tencent:mmkv-static:1.2.7**

**Comment by lingol** [comment]
We don't accept issues about `UnsatisfiedLinkError` anymore. It's clearly not the library's fault.

**Comment by mikelhm** [comment]
https://blog.csdn.net/xiaobaaidaba123/article/details/127250141?spm=1001.2014.3001.5502 this help me fix the problem.

**Comment by zhi936689039** [comment]
没用--不要问我怎么知道的

**Comment by PollexLee** [comment]
> 没用--不要问我怎么知道的

你也遇到这个问题了么？我这边是firebase上统计到的这个问题，google play分发aab，很多设备找不到.so...

**Comment by zhi936689039** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shenhe123** [comment]
我收集了一批log，用的mmkv版本是2.1.14，发现报这个crash的机型用的都是ARM Cortex-Axx系列的处理器，也是armv8_64架构，希望可以尽快解决这个问题，谢谢！

**Comment by zhi936689039** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lingol** [comment]
> 我收集了一批log，用的mmkv版本是2.1.14，发现报这个crash的机型用的都是ARM Cortex-Axx系列的处理器，也是armv8_64架构，希望可以尽快解决这个问题，谢谢！

You should open a new issue and provide your logs.

**Comment by MayDayzll** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:226)
                                                                                                    	at com.tencent.mmkv.MMKV.initialize(MMKV.java:208)
                                                                                                    	at com.tencent.mmkv.MMKV.initialize(MMKV.java:94)
                                                                                                    	at cn.com.app.jybg.app.MyApplication.onCreate(MyApplication.kt:78)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1191)  为啥还有这问题啊 怎么解决

**Comment by zhi936689039** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
