### ISSUE TITLE
使用mmkv encoding 内存溢出

### ISSUE THREAD

**Issue by jeesk** [Tencent/MMKV#965]
## Note:
oom

### The language of MMKV

> java

### The version of MMKV

> latest

### The platform of MMKV

> Android

### The installation of MMKV

> maven

### What's the issue?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shanjiancaofu.gallery.preview, PID: 8122
    java.lang.OutOfMemoryError: Failed to allocate a 274160768 byte allocation with 25165824 free bytes and 233MB until OOM, target footprint 317169480, growth limit 536870912
        at android.os.Parcel.nativeMarshall(Native Method)
        at android.os.Parcel.marshall(Parcel.java:651)
        at com.tencent.mmkv.MMKV.encode(MMKV.java:730)
        at com.shanjiancaofu.gallery.MainActivity$loadImages$1$1.invokeSuspend(MainActivity.kt:1915)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@de6cdfb, Dispatchers.Main.immediate]
```
不能存储大对象

**Comment by lingol** [comment]
It's not for storing large data.
