### ISSUE TITLE
Class not found when unmarshalling

### ISSUE THREAD

**Issue by PeOS-China** [Tencent/MMKV#983]
And here's the decoding example. I haven't tested it yet. But you get the idea.
```Java
        List<MyClass> list;
        byte[] bytes = mmkv.decodeBytes(key);
        if (bytes == null) {
            return list;
        }

        Parcel source = Parcel.obtain();
        source.unmarshall(bytes, 0, bytes.length);
        source.setDataPosition(0);
        source.readTypedList(list, MyClass.CREATOR);
        source.recycle();

        return list;
```

_Originally posted by @lingol in https://github.com/Tencent/MMKV/issues/649#issuecomment-796536271_

### **When I run the above code, sometimes the following exception occurs**

14:10:31.337 Parcel                   E  Class not found when unmarshalling: 
                                         java.lang.ClassNotFoundException: Invalid name: 
                                         	at java.lang.Class.classForName(Native Method)
                                         	at java.lang.Class.forName(Class.java:453)
                                         	at android.os.Parcel.readParcelableCreator(Parcel.java:2811)
                                         	at android.os.Parcel.readParcelable(Parcel.java:2765)
                                         	at ai.dongmi.dmdata.UserResponse$Creator.createFromParcel(Unknown Source:71)
                                         	at ai.dongmi.dmdata.UserResponse$Creator.createFromParcel(Unknown Source:0)
                                         	at android.os.Parcel.readTypedObject(Parcel.java:2614)
                                         	at android.os.Parcel.readTypedList(Parcel.java:2431)
                                         	at ai.dongmi.dmdata.manager.UserDataManager.getUserList(UserDataManager.kt:574)
                                         	at ai.dongmi.dmdata.manager.SysDataManager.checkDataVersion(SysDataManager.kt:81)
                                         	at ai.dongmi.barbell.MainActivity.initPre(MainActivity.kt:169)
                                         	at ai.dongmi.baselib.base.BaseLifeActivity.onCreate(BaseLifeActivity.kt:61)
                                         	at android.app.Activity.performCreate(Activity.java:7136)
                                         	at android.app.Activity.performCreate(Activity.java:7127)
                                         	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                         	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
                                         	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
                                         	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                         	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                         	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                         	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
                                         	at android.os.Handler.dispatchMessage(Handler.java:106)
                                         	at android.os.Looper.loop(Looper.java:193)
                                         	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
      
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/8873336/206102718-6f03c8dc-9dca-4568-ad91-54d39258842d.png">

**Comment by lingol** [comment]
I have no idea. And it's not MMKV's problem.
