### ISSUE TITLE
A crash in Harmony OS

### ISSUE THREAD

**Issue by zhangxiaojin770** [Tencent/MMKV#995]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
>Java

### The version of MMKV
> 1.2.13

### The platform of MMKV
> Harmony and Android

### The installation of MMKV
> Maven

### What's the issue?
this is a crash:
```
_Signal 7(SIGBUS), Code 2(BUS_ADRERR)
crash message: path=/data/data/com.xxx.customer/files/mmkv/COMPONENT_LOG_KV_ID, fatal_addr=00000079ee9e255c, map_addr=00000079ee9e0000-00000079ee9f0000, offset=0000000000000000
#00 pc 000000000006bae8 /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+88)
#1 pc 000000000002e784 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
#2 pc 0000000000029a60 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
#3 pc 0000000000029610 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
#4 pc 00000000000290e0 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
#5 pc 000000000001eac4 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
#6 pc 00000000000191ec /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
#7 pc 0000000000150350 /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144)
#8 pc 0000000000147334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
#9 pc 00000000001561b4 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
#10 pc 00000000002fd900 /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE+384)
#11 pc 00000000002f8bd0 /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+912)
#12 pc 00000000005cd910 /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+400)
#13 pc 0000000000141914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
#14 pc 00000000005cb874 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432)
#15 pc 0000000000141814 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20)
#16 pc 00000000005cb874 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432)
#17 pc 0000000000141814 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20)
#18 pc 00000000005cdc10 /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
#19 pc 0000000000141914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
#20 pc 00000000005ce41c /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
#21 pc 0000000000141994 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
#22 pc 00000000002ce22c /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1772238600391939451+320)
#23 pc 00000000005bc0a4 /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012)
#24 pc 0000000000150468 /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
#25 pc 00000000003d8d08 /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+984)
#26 pc 00000000003d5880 /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
#27 pc 0000000000217fc8 /system/framework/arm64/boot.oat (java.lang.Thread.run+72)
#28 pc 0000000000147334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
#29 pc 00000000001561b4 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
#30 pc 00000000004d8834 /apex/com.android.runtime/lib64/libart.so (_ZN3art12_GLOBAL__N_118InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS0_8ArgArrayEPNS_6JValueEPKc+104)
#31 pc 00000000004d98c8 /apex/com.android.runtime/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDPK6jvalue+416)
#32 pc 000000000051caa0 /apex/com.android.runtime/lib64/libart.so (_ZN3art6Thread14CreateCallbackEPv+1232)
#33 pc 00000000000cf7c0 /apex/com.android.runtime/lib64/bionic/libc.so (_ZL15__pthread_startPv+36)
#34 pc 00000000000721a8 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)_
```

### What's the log of MMKV when that happened?
I knew that more users appeared in Harmony OS

**Comment by lingol** [comment]
Crash without **symbolized** call stacks will be ignored.

**Comment by zhangxiaojin770** [comment]
at com.tencent.mmkv.MMKV.encodeSet(Native method)
at com.tencent.mmkv.MMKV.encode(SourceFile:7)
at com.geely.cockpit.framework.logger.io.LogFileManager.clearBuffer(SourceFile:2)
at com.geely.cockpit.framework.logger.io.LogFileManager.writeFlush(SourceFile:19)
at com.geely.cockpit.framework.logger.io.LogFileManager.writeToTrackLog(SourceFile:3)
at com.geely.cockpit.framework.logger.io.Track.writeToFile(SourceFile:1)
at com.geely.cockpit.framework.logger.io.Track.access$writeToFile(SourceFile:1)
at com.geely.cockpit.framework.logger.io.Track$writeAsync$1.run(SourceFile:1)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)

**Comment by zhangxiaojin770** [comment]
at com.tencent.mmkv.MMKV.encodeSet(Native method)
at com.tencent.mmkv.MMKV.encode(SourceFile:7)
at com.xxx.cockpit.framework.logger.io.LogFileManager.clearBuffer(SourceFile:2)
at com.xxx.cockpit.framework.logger.io.LogFileManager.writeFlush(SourceFile:19)
at com.xxx.cockpit.framework.logger.io.LogFileManager.writeToTrackLog(SourceFile:3)
at com.xxx.cockpit.framework.logger.io.Track.writeToFile(SourceFile:1)
at com.xxx.cockpit.framework.logger.io.Track.access$writeToFile(SourceFile:1)
at com.xxx.cockpit.framework.logger.io.Track$writeAsync$1.run(SourceFile:1)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)

**Comment by lingol** [comment]
Your native call stacks is STILL NOT symbolized.

**Comment by lingol** [comment]
Closed due to lack of information.
