### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by lchli** [Tencent/MMKV#998]
## Note:
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list for "/data/app/~~xGrigSYJWUJg0rRKJ1tjrg==/com.mexcpro.clienv-juUMUSV2WffSsrGSJCKXOA==/lib/arm64/libmmkv.so"

### The language of MMKV
java
### The version of MMKV
>  v1.2.14

### The platform of MMKV
Android
设备
品牌：OPPO
型号：CPH2325
屏幕方向： 纵向
可用 RAM： 2.59 GB
可用磁盘空间： 13.14 GB
操作系统
版本：Android 11
屏幕方向： 纵向
是否已取得 root 权限：否
崩溃
日期：2022年12月28日 22:04:46

### The installation of MMKV

Maven

### What's the issue?

Fatal Exception: java.lang.UnsatisfiedLinkError

### What's the log of MMKV when that happened?
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list for "/data/app/~~xGrigSYJWUJg0rRKJ1tjrg==/com.mexcpro.clienv-juUMUSV2WffSsrGSJCKXOA==/lib/arm64/libmmkv.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
       at com.tencent.mmkv.MMKV.initialize(MMKV.java:84)
       at com.mexc.client.mvp.ui.MyApplication.onCreate(MyApplication.java:209)
       at com.secneo.apkwrapper.AW.onCreate(AW.java:29)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7310)
       at android.app.ActivityThread.access$1700(ActivityThread.java:309)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2194)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8306)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by lingol** [comment]
We don't accept unsatisfied link errors anymore.
